sankey chart / Alluvial Diagram

In [11]:
import pandas as pd
import matplotlib as plt

In [12]:
years = [2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026]

df = pd.read_csv("data/2011-ordinance.csv")
df["year"] = 2011

for year in years:
    fh = f"data/{year}-ordinance.csv"
    dfYear = pd.read_csv(fh)
    dfYear["year"] = year
    df = pd.concat([df, dfYear], ignore_index=True)

df["amount"] = df.apply(lambda row: row["amount"] if not pd.isna(row["amount"]) else row["_ordinance_amount_"], axis=1)
df.tail()

,fund_type,fund_code,fund_description,department_number,department,department_description,appropriation_authority,appropriation_authority_description,appropriation_account,appropriation_account_description,amount,year,_ordinance_amount_,appropriation_ordinance
57023,GRANTS,925F,Federal Grant Fund,91,NaN,Chicago Public Library,280D,HUD - CPD - CPF - Rudy Lozano Branch Library R...,909A,Reserve Balance,2000000.0,2026,2000000.0,NaN
57024,GRANTS,925S,State Grant Fund,91,NaN,Chicago Public Library,2842,SOS - Capital Construction Program,909A,Reserve Balance,10050000.0,2026,10050000.0,NaN
57025,GRANTS,925S,State Grant Fund,91,NaN,Chicago Public Library,2895,SOS - Library Development - Per Capita and Area,0005,Salaries and Wages - on Payroll,5020269.0,2026,5020269.0,NaN
57026,GRANTS,925S,State Grant Fund,91,NaN,Chicago Public Library,2895,SOS - Library Development - Per Capita and Area,0015,Schedule Salary Adjustments,28808.0,2026,28808.0,NaN
57027,GRANTS,925S,State Grant Fund,91,NaN,Chicago Public Library,2895,SOS - Library Development - Per Capita and Area,0044,Fringe Benefits,3372923.0,2026,3372923.0,NaN

In [13]:
df[df["year"] == 2026]["_ordinance_amount_"].sum()

np.float64(18668568460.0)

In [14]:
funds = df[["fund_type", "fund_code", "fund_description"]].value_counts().to_frame().reset_index()
funds

,fund_type,fund_code,fund_description,count
0,LOCAL,0100,CORPORATE FUND,9063
1,LOCAL,0100,Corporate Fund,4641
2,Local,100,CORPORATE FUND,2357
3,LOCAL,0200,WATER FUND,2076
4,LOCAL,0740,O HARE REVENUE FUND,1852
...,...,...,...,...
2508,GRANTS,G665,Carbon Reduction Program,1
2509,GRANTS,G686,Advanced Transportation and Congestion Managem...,1
2510,GRANTS,G687,Hazard Mitigation Grant Program,1
2511,GRANTS,G668,Digital Equity Capacity Kickstarter Program,1
2512,LOCAL,0B67,Protecting CARE Fund,1

In [15]:
depts = df[["department_number", "department_description"]].value_counts().to_frame().reset_index()
depts

     department_number                      department_description  count
0                   99                             FINANCE GENERAL   3345
1                   41                 DEPARTMENT OF PUBLIC HEALTH   3040
2                   50                 FAMILY AND SUPPORT SERVICES   1878
3                   84                                        CDOT   1718
4                   84              CHICAGO DEPT OF TRANSPORTATION   1641
..                 ...                                         ...    ...
140                 56         INDEPENDENT POLICE REVIEW AUTHORITY     21
141                 51                PUBLIC SAFETY ADMINISTRATION     19
142                 77                                         LAC     16
143                 62                                       CCPSA      4
144                 72  Office of Climate and Environmental Equity      1

[145 rows x 3 columns]

In [16]:
authorities = df[["appropriation_authority", "appropriation_authority_description"]].value_counts().to_frame().reset_index()
authorities

,appropriation_authority,appropriation_authority_description,count
0,2005,FINANCE GENERAL,1591
1,2005.0,FINANCE GENERAL,1518
2,2005,Finance General,1372
3,2005,LAW,741
4,1005,Chicago Police Department,659
...,...,...,...
2297,2823,HUD - CPD - CDBG-DR - Stormwater Infrastructur...,1
2298,2824,HUD - CPD - CDBG-DR - Stormwater Infrastructur...,1
2299,280B,EPA - Congressionally Mandated Projects (66.202),1
2300,280D,HUD - CPD - CPF - Rudy Lozano Branch Library R...,1
2301,2842,SOS - Capital Construction Program,1

In [17]:
accounts = df[["appropriation_account", "appropriation_account_description"]].value_counts().to_frame().reset_index()
accounts

,appropriation_account,appropriation_account_description,count
0,140,PROFESSIONAL AND TECHNICAL SERVICES,2797
1,5,SALARIES AND WAGES - ON PAYROLL,2772
2,140,PROF & TECHNICAL SERVICES,1547
3,0140,For Professional and Technical Services and Ot...,1378
4,44,FRINGE BENEFITS,1312
...,...,...,...
787,9208,Domestic Violence Working Group,1
788,929C,For Accessibility Programming,1
789,921A,Group Mentoring,1
790,9259,Youth Employment,1
791,929D,Keep Chicago Clean Campaign,1