sankey chart / Alluvial Diagram

In [1]:
import pandas as pd
import matplotlib as plt

In [2]:
df = pd.read_csv("data/2026-ordinance.csv")
df.head()

,fund_type,fund_code,fund_description,department_number,department_description,appropriation_authority,appropriation_authority_description,appropriation_account,appropriation_account_description,_ordinance_amount_
0,LOCAL,0100,Corporate Fund,1,Office of the Mayor,2005,Office of the Mayor,0005,Salaries and Wages - on Payroll,10707977
1,LOCAL,0100,Corporate Fund,1,Office of the Mayor,2005,Office of the Mayor,0039,For the Employment of Students as Trainees,57490
2,LOCAL,0100,Corporate Fund,1,Office of the Mayor,2005,Office of the Mayor,0126,Office Conveniences,1500
3,LOCAL,0100,Corporate Fund,1,Office of the Mayor,2005,Office of the Mayor,0130,Postage,500
4,LOCAL,0100,Corporate Fund,1,Office of the Mayor,2005,Office of the Mayor,0140,For Professional and Technical Services and Ot...,12000

In [3]:
df["_ordinance_amount_"].sum()

np.int64(18668568460)

In [4]:
funds = df[["fund_type", "fund_code", "fund_description"]].value_counts().to_frame().reset_index()
funds

,fund_type,fund_code,fund_description,count
0,LOCAL,0100,Corporate Fund,1210
1,GRANTS,925F,Federal Grant Fund,297
2,LOCAL,0200,Water Fund,271
3,LOCAL,0740,Chicago O'Hare Airport Fund,227
4,LOCAL,0610,Chicago Midway Airport Fund,200
5,LOCAL,0300,Vehicle Tax Fund,189
6,LOCAL,0314,Sewer Fund,144
7,GRANTS,925E,Entitlement Fund,110
8,GRANTS,925S,State Grant Fund,103
9,LOCAL,0346,Library Fund,67
10,LOCAL,0353,Emergency Communication Fund,56
11,LOCAL,0355,Special Events and Municipal Hotel Operators' ...,54
12,LOCAL,0B21,Tax Increment Financing Administration Fund,48
13,GRANTS,0075,Grants Management Fund,45
14,LOCAL,0310,Motor Fuel Tax Fund,36
15,GRANTS,925L,Local Public and Private Grant Fund,36
16,GRANTS,925C,COVID-19 Grant Fund,21
17,GRANTS,GA00,Coronavirus Local Fiscal Recovery Fund,20
18,LOCAL,0D43,Neighborhoods Opportunity Fund,15
19,GRANTS,925D,Disaster Recovery Fund,15
20,LOCAL,0996,Affordable Housing Opportunity Fund,12
21,LOCAL,0B92,Construction and Demolition Debris Management ...,12
22,LOCAL,0B89,Opioid Settlement Fund,9
23,LOCAL,0B90,Vaping Settlement Fund,9
24,LOCAL,0B64,Cable Local Origination Fund,8
25,LOCAL,0B32,Garbage Collection Fund,7
26,LOCAL,0B70,Cannabis Regulation Tax,6
27,LOCAL,0B53,Wheelchair Accessible Vehicle Fund,6
28,LOCAL,0510,Bond Redemption and Interest Series Fund,3
29,LOCAL,0681,Municipal Employees' Annuity and Benefit Fund,3
30,LOCAL,0682,Laborers' and Retirement Board Annuity and Ben...,3
31,LOCAL,0683,Policemen's Annuity and Benefit Fund,3
32,LOCAL,0684,Firemen's Annuity and Benefit Fund,3
33,LOCAL,0B42,Foreign Fire Insurance Tax Fund,3
34,GRANTS,925P,Program Income Fund,3
35,LOCAL,0B93,Houseshare Surcharge - Homeless Services Fund,2
36,LOCAL,0B94,Houseshare Surcharge - Domestic Violence Fund,2
37,LOCAL,0521,Library Property Tax Levy Fund,2
38,LOCAL,0B09,CTA Real Property Transfer Tax Fund,2
39,LOCAL,0B26,Chicago Parking Meters Fund,1
40,LOCAL,0D44,Citywide Adopt-a-landmark Fund,1
41,LOCAL,0D45,Local Impact Fund,1
42,LOCAL,0994,Controlled Substances Fund,1
43,LOCAL,0B25,Chicago Police CTA Detail Fund,1
44,LOCAL,0B67,Protecting CARE Fund,1

In [5]:
depts = df[["department_number", "department_description"]].value_counts().to_frame().reset_index()
depts

,department_number,department_description,count
0,99,Finance General,347
1,84,Chicago Department of Transportation,251
2,41,Chicago Department of Public Health,232
3,15,City Council,187
4,38,Department of Fleet and Facility Management,186
5,88,Department of Water Management,170
6,50,Department of Family and Support Services,165
7,27,Department of Finance,139
8,31,Department of Law,138
9,81,Department of Streets and Sanitation,127
10,85,Chicago Department of Aviation,118
11,57,Chicago Police Department,113
12,3,Office of Inspector General,96
13,51,Office of Public Safety Administration,81
14,59,Chicago Fire Department,80
15,21,Department of Housing,70
16,72,Department of Environment,65
17,54,Department of Planning and Development,52
18,70,Department of Business Affairs and Consumer Pr...,49
19,6,Department of Technology and Innovation,45
20,58,Office of Emergency Management and Communications,45
21,48,Mayor's Office for People with Disabilities,39
22,23,Department of Cultural Affairs and Special Events,38
23,35,Department of Procurement Services,37
24,5,Office of Budget and Management,36
25,91,Chicago Public Library,36
26,28,City Treasurer's Office,35
27,25,Office of City Clerk,33
28,67,Department of Buildings,31
29,33,Department of Human Resources,30
30,1,Office of the Mayor,29
31,39,Board of Election Commissioners,28
32,62,Community Commission for Public Safety and Acc...,25
33,73,Chicago Animal Care and Control,22
34,45,Chicago Commission on Human Relations,21
35,60,Civilian Office of Police Accountability,21
36,30,Department of Administrative Hearings,18
37,78,Board of Ethics,14
38,55,Chicago Police Board,13
39,77,License Appeal Commission,6

In [6]:
authorities = df[["appropriation_authority", "appropriation_authority_description"]].value_counts().to_frame().reset_index()
authorities

,appropriation_authority,appropriation_authority_description,count
0,2005,Finance General,347
1,2005,Department of Law,135
2,2005,Office of Inspector General,96
3,2140,Bureau of Fleet Operations,82
4,1005,Chicago Police Department,74
...,...,...,...
303,2823,HUD - CPD - CDBG-DR - Stormwater Infrastructur...,1
304,2824,HUD - CPD - CDBG-DR - Stormwater Infrastructur...,1
305,280B,EPA - Congressionally Mandated Projects (66.202),1
306,280D,HUD - CPD - CPF - Rudy Lozano Branch Library R...,1
307,2842,SOS - Capital Construction Program,1

In [7]:
accounts = df[["appropriation_account", "appropriation_account_description"]].value_counts().to_frame().reset_index()
accounts

,appropriation_account,appropriation_account_description,count
0,0005,Salaries and Wages - on Payroll,250
1,0140,For Professional and Technical Services and Ot...,221
2,0015,Schedule Salary Adjustments,207
3,0044,Fringe Benefits,105
4,0350,Stationery and Office Supplies,92
...,...,...,...
246,9640,To Reimburse Corporate Fund for Costs Incurred...,1
247,0455,"For the Maintenance, Use, Benefit, and Enhance...",1
248,0526,"For the Maintenance, Use, Benefit, or Enhancem...",1
249,9287,"For Other Maintenance, Use, and Benefits for t...",1
250,0451,For Purchase of Vehicles for Use by the Police...,1