sankey chart / Alluvial Diagram

In [1]:
# imports
import pandas as pd
import matplotlib as plt
import math

In [2]:
# set display options for pandas
pd.set_option("display.max_rows", None)
pd.set_option("display.max_colwidth", None)

In [3]:
# constants
years = [2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026]
normalizedColumns = ["fund_type", "fund_description", "department_description", "appropriation_authority_description",  "appropriation_account_description"]

In [4]:
# helper functions
def getRowAmount(row):
    if not pd.isna(row["_ordinance_amount_"]):
        return row["_ordinance_amount_"]
    elif not pd.isna(row["appropriation_ordinance"]):
        return row["appropriation_ordinance"]
    else:
        return row["amount"]

def getValueCounts(cols):
    return df[cols].value_counts().to_frame().reset_index()

def getAltNames(df, indexCol, nameCol):
    count = df[indexCol].value_counts().to_frame().reset_index()
    mult = count[count["count"] > 1]
    mult["names"] = mult.apply(lambda row: df[df[indexCol] == row[indexCol]][nameCol].to_list(), axis=1)
    return mult

def getAnnualBudget(df, year):
    return df[df["year"] == year]["amount"].sum()

In [21]:
# import all ordinance files and combine into table
df = pd.DataFrame()
for year in years:
    dfYear = pd.read_csv(f"data/{year}-ordinance.csv")
    dfYear["year"] = year
    df = pd.concat([df, dfYear], ignore_index=True)


# clean rows and columns
df["amount"] = df.apply(getRowAmount, axis=1)
df["fund_code"] = df.apply(lambda row: row["fund_code"] if len(row["fund_code"]) == 4 else "0" + row["fund_code"], axis=1)
df["appropriation_authority"] = df["appropriation_authority"].apply(lambda x: str(int(x)) if isinstance(x, float) and not math.isnan(x) else x)
df = df.drop(columns=["department", "_ordinance_amount_", "appropriation_ordinance"])

for colName in normalizedColumns:
    df[colName] = df[colName].str.upper()

df.tail()

,fund_type,fund_code,fund_description,department_number,department_description,appropriation_authority,appropriation_authority_description,appropriation_account,appropriation_account_description,amount,year
57023,GRANTS,925F,FEDERAL GRANT FUND,91,CHICAGO PUBLIC LIBRARY,280D,HUD - CPD - CPF - RUDY LOZANO BRANCH LIBRARY RENOVATION (14.251),909A,RESERVE BALANCE,2000000.0,2026
57024,GRANTS,925S,STATE GRANT FUND,91,CHICAGO PUBLIC LIBRARY,2842,SOS - CAPITAL CONSTRUCTION PROGRAM,909A,RESERVE BALANCE,10050000.0,2026
57025,GRANTS,925S,STATE GRANT FUND,91,CHICAGO PUBLIC LIBRARY,2895,SOS - LIBRARY DEVELOPMENT - PER CAPITA AND AREA,0005,SALARIES AND WAGES - ON PAYROLL,5020269.0,2026
57026,GRANTS,925S,STATE GRANT FUND,91,CHICAGO PUBLIC LIBRARY,2895,SOS - LIBRARY DEVELOPMENT - PER CAPITA AND AREA,0015,SCHEDULE SALARY ADJUSTMENTS,28808.0,2026
57027,GRANTS,925S,STATE GRANT FUND,91,CHICAGO PUBLIC LIBRARY,2895,SOS - LIBRARY DEVELOPMENT - PER CAPITA AND AREA,0044,FRINGE BENEFITS,3372923.0,2026

In [ ]:
# More Info from 2026 Budget Breakdown: https://public.tableau.com/app/profile/obm.data.analytics/viz/CityofChicago-BudgetataGlance/ChicagoBudgetataGlance?publish=yes
# Proceeds of debt issuances transferred between funds and reimbursements or internal transfers between funds need to be deducted to more accurately reflect the City appropriation.
# Total resources include revenues generated during the year.
budgets = pd.DataFrame({ "year": years, "budget": list(map(lambda x: int(getAnnualBudget(df, x)), years))})
budgets

    year       budget
0   2011   8700334637
1   2012   8614865000
2   2013   8745336000
3   2014   9114711000
4   2015   9555106000
5   2016  10056354000
6   2017  10677480000
7   2018  10752004000
8   2019  11400085000
9   2020  12607102000
10  2021  13522521000
11  2022  18115873000
12  2023  17974994000
13  2024  18341105000
14  2025  18842061980
15  2026  18668568460

In [ ]:
# More Info from Office of Inspector General: https://igchicago.org/information-portal/data-dashboards/city-budget-by-departments/
# Local funds are used by the City for non-capital operations with sources other than grant funds. These include the Corporate Fund, O’Hare Revenue Fund, Water Fund, and other similar funds. 
# Grants are financial awards given by the federal, state, or local government authority restricted for a specific project or service. 
# Community Development Block Grant (CDBG) funds are provided by federal and state governments to communities and people to be used in a variety of ways including housing, community development programs, healthy food initiatives, and sustainability services. 
funds = getValueCounts(["fund_type", "fund_code", "fund_description"])
funds.head(10)

  fund_type fund_code             fund_description  count
0     LOCAL      0100               CORPORATE FUND  18603
1     LOCAL      0200                   WATER FUND   4317
2     LOCAL      0300                 VEHICLE FUND   2794
3     LOCAL      0610          MIDWAY AIRPORT FUND   2250
4     LOCAL      0314                   SEWER FUND   2185
5     LOCAL      0740          O HARE REVENUE FUND   1852
6     LOCAL      0740          O'HARE REVENUE FUND    937
7     LOCAL      0740  CHICAGO O'HARE AIRPORT FUND    897
8     LOCAL      0346                 LIBRARY FUND    871
9     LOCAL      0610  CHICAGO MIDWAY AIRPORT FUND    804

In [20]:
depts = getValueCounts(["department_number", "department_description"])
depts

,department_number,department_description,count
0,99,FINANCE GENERAL,4717
1,41,DEPARTMENT OF PUBLIC HEALTH,3040
2,50,FAMILY AND SUPPORT SERVICES,1878
3,31,DEPARTMENT OF LAW,1827
4,84,CDOT,1718
5,84,CHICAGO DEPT OF TRANSPORTATION,1641
6,50,DFSS,1541
7,27,FINANCE,1458
8,15,CITY COUNCIL,1390
9,57,DEPARTMENT OF POLICE,1365
10,41,CHICAGO DEPARTMENT OF PUBLIC HEALTH,1224
11,84,CHICAGO DEPARTMENT OF TRANSPORTATION,1016
12,41,HEALTH,992
13,81,DEPT STREETS AND SANITATION,955
14,88,DEPT OF WATER MANAGEMENT,952
15,54,PLANNING AND DEVELOPMENT,895
16,57,CPD,893
17,85,DEPARTMENT OF AVIATION,842
18,58,OEMC,837
19,50,DEPARTMENT OF FAMILY AND SUPPORT SERVICES,824
20,57,CHICAGO POLICE DEPARTMENT,774
21,31,LAW,755
22,81,DSS,720
23,88,DWM,707
24,3,OIG,667
25,27,DEPARTMENT OF FINANCE,657
26,88,DEPARTMENT OF WATER MANAGEMENT,616
27,38,FLEET AND FACILITY MGMT,604
28,38,FLEET AND FACILITY MANAGEMENT,599
29,54,HOUSING AND ECONOMIC DEVELOPMT,571
30,38,DEPARTMENT OF FLEET AND FACILITY MANAGEMENT,560
31,41,CDPH,540
32,59,FIRE DEPARTMENT,503
33,59,CFD,503
34,81,DEPARTMENT OF STREETS AND SANITATION,495
35,85,CHICAGO DEPARTMENT OF AVIATION,479
36,91,CHICAGO PUBLIC LIBRARY,471
37,38,AIS,451
38,59,CHICAGO FIRE DEPARTMENT,448
39,3,OFFICE OF INSPECTOR GENERAL,404
40,33,DEPARTMENT OF HUMAN RESOURCES,398
41,48,MOPD,395
42,38,FFM,374
43,85,AVIATION,362
44,21,DEPARTMENT OF HOUSING,356
45,3,IG,354
46,1,OFFICE OF THE MAYOR,334
47,51,OFFICE OF PUBLIC SAFETY ADMINISTRATION,334
48,67,DEPT OF BUILDINGS,331
49,81,STREETS AND SANITATION,319
50,23,DCASE,314
51,25,CITY CLERK,309
52,6,DOIT,309
53,5,OBM,308
54,70,BACP,304
55,88,WATER MANAGEMENT,297
56,23,CULTURAL AFFAIRS SPECIAL EVENT,283
57,45,COMMISSION ON HUMAN RELATIONS,273
58,27,DOF,269
59,67,DEPARTMENT OF BUILDINGS,260
60,48,MAYORS OFFICE-DISABILITIES,251
61,54,DEPARTMENT OF PLANNING AND DEVELOPMENT,249
62,5,OFFICE OF BUDGET & MANAGEMENT,248
63,38,DEPARTMENT OF ASSETS INFORMATION AND SERVICES,246
64,21,DOH,233
65,85,CDA,233
66,58,OFFICE OF EMERGENCY MANAGEMENT AND COMMUNICATIONS,233
67,70,BUS AFFAIRS AND CONSUMER PROT,222
68,21,HOUSING,219
69,38,DAIS,211
70,23,DEPARTMENT OF CULTURAL AFFAIRS AND SPECIAL EVENTS,210
71,91,CPL,205
72,48,MAYOR'S OFFICE FOR PEOPLE WITH DISABILITIES,205
73,70,DEPARTMENT OF BUSINESS AFFAIRS AND CONSUMER PROTECTION,200
74,6,DEPARTMENT OF TECHNOLOGY AND INNOVATION,199
75,39,BOARD OF ELECTION COMMISSIONER,192
76,35,DPS,184
77,28,CITY TREASURER,180
78,72,DEPARTMENT OF ENVIRONMENT,171
79,15,COUNCIL,169
80,78,BOARD OF ETHICS,167
81,5,OFFICE OF BUDGET AND MANAGEMENT,162
82,51,PSA,158
83,35,DEPARTMENT OF PROCUREMENT SERV,155
84,67,BUILDINGS,152
85,55,POLICE BOARD,149
86,35,DEPARTMENT OF PROCUREMENT SERVICES,146
87,33,DHR,145
88,54,DPD,144
89,28,CITY TREASURER'S OFFICE,142
90,73,COMM ANIMAL CARE AND CONTROL,141
91,39,ELECTIONS,138
92,25,OFFICE OF CITY CLERK,133
93,38,GENERAL SERVICES,125
94,28,TREASURER,123
95,45,CHICAGO COMMISSION ON HUMAN RELATIONS,121
96,40,DEPARTMENT OF FLEET MANAGEMENT,120
97,60,COPA,116
98,39,BOARD OF ELECTION COMMISSIONERS,112
99,30,ADMINISTRATIVE HEARINGS,101
100,58,OFFICE OF EMERGENCY MANAGEMENT & COMMUNICATIONS,100
101,30,DEPT OF ADMINISTRATIVE HEARING,99
102,45,HUMAN RELATIONS,99
103,62,COMMUNITY COMMISSION FOR PUBLIC SAFETY AND ACCOUNTABILITY,99
104,56,IPRA,97
105,1,MAYOR,95
106,3,INSPECTOR GENERAL,93
107,77,LICENSE APPEAL COMMISSION,93
108,67,DOB,91
109,73,CHICAGO ANIMAL CARE AND CONTROL,90
110,73,ANIMAL CARE / CONTROL,83
111,60,CIVILIAN OFFICE OF POLICE ACCOUNTABILITY,80
112,78,ETHICS,74
113,28,CTO,74
114,30,DEPARTMENT OF ADMINISTRATIVE HEARINGS,72
115,25,CLERK,71
116,35,PROCUREMENT SERVICES,63
117,45,CCHR,62
118,29,DEPARTMENT OF REVENUE,55
119,6,DEPARTMENT OF INNOVATION AND TECHNOLOGY,55
120,73,ANIMAL CARE AND CONTROL,52
121,55,CHICAGO POLICE BOARD,52
122,1,MO,51
123,73,CACC,48
124,30,DOAH,39
125,32,OFFICE OF COMPLIANCE,30
126,77,LICENSE APPEAL,28
127,56,INDEPENDENT POLICE REVIEW AUTHORITY,21
128,51,PUBLIC SAFETY ADMINISTRATION,19
129,77,LAC,16
130,62,CCPSA,4
131,72,OFFICE OF CLIMATE AND ENVIRONMENTAL EQUITY,1

In [9]:
authorities = getValueCounts(["appropriation_authority", "appropriation_authority_description"])
authorities.head()

  appropriation_authority appropriation_authority_description  count
0                    2005                     FINANCE GENERAL   4481
1                    2005         OFFICE OF INSPECTOR GENERAL   1425
2                    2005                   DEPARTMENT OF LAW   1188
3                    2005                                 LAW   1073
4                    2131          BUREAU OF ASSET MANAGEMENT    927

In [10]:
accounts = getValueCounts(["appropriation_account", "appropriation_account_description"])
accounts.head()

,appropriation_account,appropriation_account_description,count
0,140,PROFESSIONAL AND TECHNICAL SERVICES,2797
1,5,SALARIES AND WAGES - ON PAYROLL,2772
2,140,PROF & TECHNICAL SERVICES,1547
3,0140,FOR PROFESSIONAL AND TECHNICAL SERVICES AND OTHER THIRD PARTY BENEFIT AGREEMENTS,1378
4,44,FRINGE BENEFITS,1312

In [11]:
multFundCodes = getAltNames(funds, "fund_code", "fund_description")
multFundCodes.head()

,fund_code,count,names
0,0740,3,"[O HARE REVENUE FUND, O'HARE REVENUE FUND, CHICAGO O'HARE AIRPORT FUND]"
1,0521,3,"[LIB NOTE RED/INT-B, LIBRARY NOTE REDEMPTION AND INTEREST TENDER NOTES SERIES ""B"" FUND, LIBRARY PROPERTY TAX LEVY FUND]"
2,0510,3,"[BOND REDEMPTION AND INTEREST, BOND REDMPTN/IN F, BOND REDEMPTION AND INTEREST SERIES FUND]"
3,0681,3,"[MUNICIPAL ANNUNITY AND BENEFIT, MUNICIPAL EMPLOYEES' ANNUITY AND BENEFIT FUND, MUNICIPAL EMPLOYEE]"
4,0682,3,"[LABORERS' AND RETIREMENT BOARD ANNUITY AND BENEFIT FUND, LABORERS' ANNUNITY AND BENEFIT, LABORERS'/RETIREMNT]"

In [12]:
multDeptNums = getAltNames(depts, "department_number", "department_description")
multDeptNums.head()

,department_number,count,names
0,38,8,"[FLEET AND FACILITY MGMT, FLEET AND FACILITY MANAGEMENT, DEPARTMENT OF FLEET AND FACILITY MANAGEMENT, AIS, FFM, DEPARTMENT OF ASSETS INFORMATION AND SERVICES, DAIS, GENERAL SERVICES]"
1,73,5,"[COMM ANIMAL CARE AND CONTROL, CHICAGO ANIMAL CARE AND CONTROL, ANIMAL CARE / CONTROL, ANIMAL CARE AND CONTROL, CACC]"
2,41,4,"[DEPARTMENT OF PUBLIC HEALTH, CHICAGO DEPARTMENT OF PUBLIC HEALTH, HEALTH, CDPH]"
3,81,4,"[DEPT STREETS AND SANITATION, DSS, DEPARTMENT OF STREETS AND SANITATION, STREETS AND SANITATION]"
4,88,4,"[DEPT OF WATER MANAGEMENT, DWM, DEPARTMENT OF WATER MANAGEMENT, WATER MANAGEMENT]"

In [13]:
multAuthorities = getAltNames(authorities, "appropriation_authority", "appropriation_authority_description")
multAuthorities.head()

,appropriation_authority,count,names
0,2005,93,"[FINANCE GENERAL, OFFICE OF INSPECTOR GENERAL, DEPARTMENT OF LAW, LAW, CHICAGO FIRE DEPARTMENT, COMMISSIONER'S OFFICE, CHICAGO PUBLIC LIBRARY, FIRE DEPARTMENT, PLANNING AND DEVELOPMENT, FAMILY AND SUPPORT SERVICES, ELECTION AND ADMIN DIVISION, CITY CLERK, CITY TREASURER, OFFICE OF THE MAYOR, BUILDINGS, OFFICE OF PUBLIC SAFETY ADMINISTRATION, DEPARTMENT OF HUMAN RESOURCES, PROCUREMENT SERVICES, 2005 - FINANCE GENERAL, BACP, BOARD OF ETHICS, HUMAN RESOURCES, OFFICE OF CITY CLERK, DOIT, DEPT OF BUILDINGS, 2005 - DEPARTMENT OF LAW, ANIMAL CARE AND CONTROL, CITY COUNCIL, DEPARTMENT OF PLANNING AND DEVELOPMENT, DEPARTMENT OF PROCUREMENT SERVICES, OFFICE OF CITY TREASURER, ADMINISTRATIVE HEARINGS, PUBLIC SAFETY ADMINISTRATION, DEPARTMENT OF FAMILY AND SUPPORT SERVICES, BUS AFFAIRS AND CONSUMER PROT, DEPARTMENT OF BUSINESS AFFAIRS AND CONSUMER PROTECTION, LICENSE APPEAL COMMISSION, DEPARTMENT OF BUILDINGS, DEPARTMENT OF PROCUREMENT SERV, MOPD, OBM, COPA, ELECTION AND ADMINISTRATION DIVISION, POLICE BOARD, COMM ANIMAL CARE AND CONTROL, COMMUNITY COMMISSION FOR PUBLIC SAFETY AND ACCOUNTABILITY, IPRA, HUMAN RELATIONS, 2005 - OFFICE OF INSPECTOR GENERAL, CHICAGO ANIMAL CARE AND CONTROL, HOUSING AND ECONOMIC DEVELOPMT, CIVILIAN OFFICE OF POLICE ACCOUNTABILITY, 2005 - FIRE DEPARTMENT, DEPT OF ADMINISTRATIVE HEARING, CHICAGO POLICE BOARD, OFFICE FOR PEOPLE WITH DISABIL, 2005 - CITY COMPTROLLER, OFFICE OF BUDGET & MANAGEMENT, DEPARTMENT OF ADMINISTRATIVE HEARINGS, CITY TREASURER'S OFFICE, COMMISSION ON HUMAN RELATIONS, OFFICE OF BUDGET AND MANAGEMENT, 2005 - DEPT OF BUILDINGS, MAYOR'S OFFICE FOR PEOPLE WITH DISABILITIES, CHICAGO COMMISSION ON HUMAN RELATIONS, 2005 - COMMISSIONER'S OFFICE, 2005 - DEPARTMENT OF HUMAN RESOURCES, 2005 - HOUSING AND ECONOMIC DEVELOPMT, 2005 - FAMILY AND SUPPORT SERVICES, 2005 - BUS AFFAIRS AND CONSUMER PROT, 2005 - DEPARTMENT OF ENVIRONMENT, 2005 - DEPARTMENT OF PROCUREMENT SERV, 2005 - CHICAGO PUBLIC LIBRARY, 2005 - ELECTION AND ADMIN DIVISION, 2005 - CITY CLERK, 2005 - COMM ANIMAL CARE AND CONTROL, 2005 - DOIT, 2005 - OFFICE OF COMPLIANCE, 2005 - BUREAU OF CULTURAL AFFAIRS, 2005 - CITY TREASURER, 2005 - DEPT OF ADMINISTRATIVE HEARING, 2005 - IPRA, 2005 - COMMISSION ON HUMAN RELATIONS, 2005 - OFFICE OF BUDGET & MANAGEMENT, 2005 - OFFICE FOR PEOPLE WITH DISABIL, 2005 - OFFICE OF THE MAYOR, 2005 - BOARD OF ETHICS, 2005 - CITY COUNCIL, 2005 - POLICE BOARD, 2005 - LICENSE APPEAL COMMISSION, CCPSA, 2005 - COMMISSIONERS OFFICE, COMMISSIONERS OFFICE]"
1,2800,30,"[INNOVATION DELIVERY GRANT, AMPLIFIED PHONES PROGRAM, CENTRAL GRANTS MANAGEMENT, DHS ACCOUNTING, O'HARE - FAA (MOA) - PHASE II, CTY - GRANTS MANAGEMENT, 2800 - AVIATION ENVIRONMENTAL AND RE, MICD, NEIGHBORHOOD STABILIZATION PRO, HAZARD MITIGATION PROGRAM, 2800 - DHS ACCOUNTING, HEALTH IT COORDINATOR, 2800 - TRAFFIC SIGNALS/STREET LIGHTS, 2800 - EDGEWATER BRANCH - CAPITAL, 2800 - MICD, 2800 - O'HARE - FAA (MOA) - PHASE II, 2800 - ARRA - CHICAGO ALT. FUELS, 2800 - HEALTH IT COORDINATOR, 2800 - GREAT LAKES RESTORATION, 2800 - NEIGHBORHOOD STABILIZATION PRO, 2800 - ARRA PORT SECURITY GRANT PROGR, 2800 - LABOR MGMT. HEALTH CARE SAVING, EDGEWATER BRANCH - CAPITAL, URBAN BIRD TREATY, ARRA PORT SECURITY GRANT PROGR, HELP AMERICA VOTE ELECTION SEC, HEALTH DISPARITIES CHICAGO, TREE PLANTING, STATE URBAN FORESTRY RESILIENCE (TREE PLANTING), CLIR RECORDINGS AT RISK PROGRAM]"
2,2505,26,"[ADMINISTRATION AND MONITORING, FINANCE AND ADMINISTRATION, DISABILITY RESOURCES, EDUCATION OUTREACH AND INTERG, TROUBLED BUILDINGS PROGRAM, ENVIRONMENTAL REVIEW, PLANNING AND ADMINISTRATION, 2505 - FINANCE AND ADMINISTRATION, EDUCATION OUTREACH AND INTERGROUP, COMMUNITY ENHANCEMENT, PLANNING AND ADMINISTRATION, LEGAL SERVICES, 2505 - ADMINISTRATION AND MONITORING, 2505 - EDUCATION OUTREACH AND INTERG, 2505 - DISABILITY RESOURCES, 2505 - SPECIAL ACCOUNTING DIVISION, HUD - CPD - CDBG - PLANNING AND ADMINISTRATION (14.218), 2505 - TROUBLED BUILDINGS PROGRAM, 2505 - LEGAL SERVICES, EDUCATION OUTREACH AND INTERGP, LEAD SERVICE LINE REPLACEMENT, YOUTH SERVICES, 2505 - YOUTH SERVICES, COMMUNITY POLICING, 2505 - COMPLIANCE AUDITS, HUD - CPD - CDBG - REHABILITATION - LEAD SERVICE LINE REPLACEMENT (14.218)]"
3,2805,25,"[CSBG, COMMUNITY SERVICES BLOCK GRANT, SUBSTANCE ABUSE/AIDS PREV-H.I., SUBSTANCE PREVENTION USE DEAF, 2805 - CSBG, AIP-MIDWAY, HHS - ACF - DCEO - COMMUNITY SERVICES BLOCK GRANT (93.569), NTL FORUM YOUTH VIOLENCE PREV., SUBSTANCE ABUSE PREVENTION, CONGESTION MITIGATION AIR QUALITY (CMAQ), CONG MITIG AIR QUAL-FEDERAL, CMAQ - FEDERAL, CMAQ, HHS - SAMHSA - IDHS - CTY - SUBSTANCE ABUSE PREVENTION PROGRAM (93.959), 2805 - LOCAL TOURISM CONVENTION, 2805 - SUBSTANCE ABUSE/AIDS PREV-H.I., MIDWAY - AIRPORT IMPROVEMENT PROGRAM, 2805 - RESOURCE CONS/RECOV ACT-ST D, 2805 - CONG MITIG AIR QUAL-FEDERAL, INTEGRATED GULL MANAGEMENT, DOT - FAA - AIRPORT IMPROVEMENT PROGRAM - MIDWAY (20.106), 2805 - AIP-MIDWAY, 2805 - UNDERGROUND STOR TANK INSPECT, DOG RESCUE PROJECT, DCEO - BROADBAND CONNECT ILLINOIS]"
4,2820,21,"[IMMUNIZATIONS, IMMUNIZATION, VACCINE PREVENTABLE DISEASES, LONGTERM CARE SYSTEM DEVELOP, 2820 - IMMUNIZATION, EMERGENCY MGMT ASSISTANCE, SECURING THE CITY, SURFACE TRANSPORTATION PROGRAM (STP), STP FEDERAL CONSTRUCTION, HHS - CDC - IMMUNIZATION (93.268), LONG TERM CARE SYSTEM DEVELOPMENT, FIBER CONNECTION GRANT, STP, EMERGENCY MANAGEMENT ASSISTANCE, 2820 - LONGTERM CARE SYSTEM DEVELOP, LABOR MANAGEMENT COOPERATION, EMPOWERED CITIES, EMPOWERED CITIES INITIATIVE, 2820 - STP FEDERAL CONSTRUCTION, 2820 - FIBER CONNECTION GRANT, DHS - FEMA - IEMA - EMERGENCY MANAGEMENT PERFORMANCE GRANTS (97.042)]"

In [14]:
multAccounts = getAltNames(accounts,"appropriation_account", "appropriation_account_description")
multAccounts.head()

,appropriation_account,count,names
0,9438,4,"[REIMBURSEMENT - 2FM, REIMBURSEMENT - DGS, REIMBURSEMENT - AIS, REIMBURSEMENT - DAIS]"
1,9771,4,"[TRANSFER FOR SERVICES - 2FM, TRANSFER FOR SERVICES - AIS, TRANSFER FOR SERVICES 2FM, TRANSFER FOR SERVICES - DAIS]"
2,190,3,"[TELEPHONE - NON-CENTREX BILLINGS, TELEPHONE-CENTREX, TELEPHONE - CENTREX BILLINGS]"
3,989,3,"[REFUND - CANCELLED VOUCHER, REFUND CANCELLED VOUCHR, REFUND CANCELLED VOUCHER]"
4,17,3,"[CITY COUNCIL - SALARIED EMPLOYEES, CITY COUNCIL-SALARY INC, WARD STAFF WAGE ALLOWANCE]"