In [1]:
# imports
import pandas as pd
import math

# display options
pd.set_option("display.max_rows", None)
pd.set_option("display.max_colwidth", None)
pd.set_option("display.float_format", "{:.2f}".format)

In [2]:
# labels
categories = {
    "City Development": ["21", "23", "54"],
    "Infrastructure Services": ["81", "84", "85", "88"],
    "Community Services": ["41", "45", "48", "50", "91", "32"],
    "Legislative & Elections": ["15", "39"],
    "Finance & Administration": [
        "01",
        "05",
        "06",
        "25",
        "27",
        "28",
        "30",
        "31",
        "33",
        "35",
        "38",
        "40",
        "29",
    ],
    "Public Safety": ["51", "55", "56", "57", "58", "59", "60", "62"],
    "General Financing": ["99"],
    "Regulatory": ["03", "67", "70", "72", "73", "77", "78"],
}

depts = [
    "01 - OFFICE OF THE MAYOR",
    "03 - OFFICE OF THE INSPECTOR GENERAL",
    "05 - BUDGET AND MANAGEMENT",
    "06 - TECHNOLOGY AND INNOVATION",
    "15 - CITY COUNCIL",
    "21 - DEPARTMENT OF HOUSING",
    "23 - CULTURAL AFFAIRS AND SPECIAL EVENTS",
    "25 - CITY CLERK",
    "27 - FINANCE",
    "28 - CITY TREASURER'S OFFICE",
    "29 - DEPARTMENT OF REVENUE",
    "30 - ADMINISTRATIVE HEARINGS",
    "31 - LAW",
    "32 - OFFICE OF COMPLIANCE",
    "33 - HUMAN RESOURCES",
    "35 - PROCUREMENT SERVICES",
    # "38 - ASSETS, INFORMATION, AND SERVICES (AIS)", ?????????
    # "38 - GENERAL SERVICES",
    "38 - FLEET & FACILITY MANAGEMENT",
    "39 - BOARD OF ELECTIONS COMMISSIONERS",
    "40 - DEPARTMENT OF FLEET MANAGEMENT",
    "41 - HEALTH",
    "45 - COMMISSION ON HUMAN RELATIONS",
    "48 - MAYOR'S OFFICE FOR PEOPLE WITH DISABILITIES",
    "50 - FAMILY & SUPPORT SERVICES",
    "51 - PUBLIC SAFETY ADMINSTRATION",
    "54 - PLANNING AND DEVELOPMENT",
    "55 - CHICAGO POLICE BOARD",
    "56 - INDEPENDENT POLICE REVIEW AUTHORITY (IPRA)",
    "57 - CHICAGO POLICE DEPARTMENT",
    "58 - EMERGENCY MANAGEMENT COMMUNICATION",
    "59 - CHICAGO FIRE DEPARTMENT",
    "60 - CIVILIAN OFFICE OF POLICE ACCOUNTABILITY",
    "62 - COMMUNITY COMMISION FOR PUBLIC SAFETY AND ACCOUNTABILITY",
    "67 - BUILDINGS",
    "70 - BUSINESS AFFAIRS AND CONSUMER PROTECTION",
    "72 - ENVIRONMENT",
    "73 - ANIMAL CARE & CONTROL",
    "77 - LICENSE APPEAL COMMISSION",
    "78 - BOARD OF ETHICS",
    "81 - STREETS AND SANITATION",
    "84 - CHICAGO DEPARTMENT OF TRANSPORTATION",
    "85 - AVIATION",
    "88 - WATER MANAGEMENT",
    "91 - PUBLIC LIBRARY",
    "99 - FINANCE GENERAL",
]

accounts = [
    "0000 - Personnel Services",
    "0003 - Scheduled Wage Adjustments",
    "0005 - Salaries and Wages - on Payroll",
    "0006 - Salary Provision",
    "0008 - For Payment of Retroactive Salaries",
    "0012 - Contract Wage Increment - Prevailing Rate",
    "0015 - Schedule Salary Adjustments",
    "0017 - Wage Allowance for Aldermanic Ward Staff (up to Four Full-Time Salaried Employees Per Alderman)",
    "0020 - Overtime",
    "0021 - Sworn/Civilian Holiday Premium Pay",
    "0022 - Duty Availability",
    "0024 - Compensatory Time Payment",
    "0027 - Supervisors Quarterly Payment",
    "0028 - Cooperative Education Program",
    "0029 - For Health Maintenance Organization Premiums (HMO) Provided to Eligible Employees and Their Families",
    "0032 - Reimbursable Overtime",
    "0039 - For the Employment of Students as Trainees",
    "0042 - CLAIMS AND ADMIN FOR HOSP AND MED CARE PROVIDED TO ELIGIBLE EMPLOYEES",
    "0043 - HMO PREM, CLAIMS, AND ADMIN FOR SWORN POLICE AND FIRE ON DUTY/OCCUP DISABILITY",
    "0044 - Fringe Benefits",
    "0045 - For the Cost of Claims and Administration or Premiums for Term Life Insurance",
    "0049 - Claims and Costs of Administration Pursuant to the Workers' Compensation Act",
    "0050 - Stipends",
    "0051 - Claims Under Unemployment Insurance Act",
    "0052 - Costs of Claims and Administration for Hospital and Medical Care to Eligible Annuitants and Their Eligible Dependents",
    "0055 - Extra Hire",
    "0056 - For the Cost of Claims and Administration or Premiums for a Co-Insured Dental Plan for Employees",
    "0060 - Specialty Pay",
    "0061 - Driver's Differential",
    "0062 - Required Certifications",
    "0063 - Fitness Benefit",
    "0070 - Tuition Reimbursement and Educational Programs",
    "0085 - City Deferred Compensation Contributions for Union Members",
    "0088 - Furlough/Supervisors Compensation Time Buy-Back",
    "0091 - Uniform Allowance",
    "0095 - For Payment of Allowances of Money to Families or Dependents of Policemen or Firemen Fatally Injured While in the Performance of Their Duties",
    "0096 - 1-YEAR SALARY FOR SWORN POLICE OR FIRE MEMBER KILLED IN THE LINE OF DUTY",
    "0100 - Contractual Services",
    "0123 - For Services Provided by Performers and Exhibitors",
    "0124 - Investigation Costs",
    "0125 - Office and Building Services",
    "0126 - Office Conveniences",
    "0128 - Investigation Costs. To Be Expended at the Direction of the Comptroller",
    "0130 - Postage",
    "0135 - For Delegate Agencies",
    "0138 - For Professional Services for Information Technology Maintenance",
    "0139 - For Professional Services for Information Technology Development",
    "0140 - For Professional and Technical Services and Other Third Party Benefit Agreements",
    "0141 - Appraisals",
    "0142 - Accounting and Auditing",
    "0143 - Court Reporting",
    "0144 - Engineering and Architecture",
    "0145 - Legal Expenses",
    "0147 - Surveys",
    "0148 - Testing and Inspecting",
    "0149 - For Software Maintenance and Licensing",
    "0150 - Publications and Reproduction - Outside Services. To be Expended with the Prior Approval of Graphics Services",
    "0152 - Advertising",
    "0153 - Promotions",
    "0154 - For the Rental and Maintenance of Data Processing, Office Automation and Data Communications Hardware",
    "0155 - Rental of Property",
    "0156 - Lock Box Rental",
    "0157 - Rental of Equipment and Services",
    "0159 - Lease Purchase Agreements for Equipment and Machinery",
    "0160 - Repair or Maintenance of Property",
    "0161 - Operation, Repair or Maintenance of Facilities",
    "0162 - Repair/Maintenance of Equipment",
    "0163 - Repair/Maintenance of Streets and Pavements",
    "0164 - Bookbinding",
    "0165 - Graphic Design Services",
    "0166 - Dues, Subscriptions and Memberships",
    "0168 - Educational Development through Cooperative Education Program and Apprenticeship Program",
    "0169 - Technical Meeting Costs",
    "0170 - Surety Bond Premiums",
    "0171 - Miscellaneous Supplies",
    "0172 - For the Cost of Insurance Premiums and Expenses",
    "0176 - Maintenance and Operation of City Owned Vehicles",
    "0178 - Freight and Express Charges",
    "0179 - Messenger Service",
    "0181 - Mobile Communication Services",
    "0183 - Water",
    "0185 - Waste Disposal Services",
    "0188 - Vehicle Tracking Service",
    "0189 - Telephone - Non-Centrex Billings",
    "0190 - Telephone - Centrex Billings",
    "0191 - Telephone - Relocations of Phone Lines",
    "0196 - Data Circuits",
    "0197 - Telephone - Maintenance and Repair of Equipment and Voicemail",
    "0228 - Out of Town Travel for Auditors Only",
    "0229 - Transportation and Expense Allowance",
    "0245 - Reimbursement to Travelers",
    "0270 - Local Transportation",
    "0300 - Commodities and Materials",
    "0312 - Software Purchases",
    "0313 - Cleaning and Sanitation Supplies",
    "0314 - Fuel Oil",
    "0315 - Motor Vehicle Diesel Fuel",
    "0316 - Gas - Bottled and Propane",
    "0318 - Other Fuel",
    "0319 - Clothing",
    "0320 - Gasoline",
    "0322 - Natural Gas",
    "0325 - Alternative Fuel",
    "0330 - Food",
    "0331 - Electricity",
    "0332 - Electricity - Street Lighting",
    "0338 - License Sticker, Tag and Plates",
    "0339 - Revenue Stamps",
    "0340 - Material and Supplies",
    "0341 - Chemicals",
    "0342 - Drugs, Medicine and Chemical Materials",
    "0345 - Apparatus and Instruments",
    "0348 - Books and Related Material",
    "0350 - Stationery and Office Supplies",
    "0360 - Repair Parts and Material",
    "0361 - Building Materials and Supplies",
    "0362 - Paints and Painting Supplies",
    "0364 - Plumbing Supplies",
    "0365 - Electrical Supplies",
    "0400 - Equipment",
    "0401 - TOOLS LESS THAN OR EQUAL TO $100",
    "0402 - TOOLS GREATER THAN $100",
    "0410 - Equipment for Buildings",
    "0420 - Furniture and Fixtures",
    "0421 - Machinery and Equipment",
    "0422 - Office Machines",
    "0423 - Communication Devices",
    "0424 - Furniture and Furnishings",
    "0430 - Livestock",
    "0440 - Machinery and Equipment",
    "0445 - Technical and Scientific Equipment",
    "0446 - For the Purchase of IT and Data Communication Hardware",
    "0450 - Vehicles",
    "0451 - For Purchase of Vehicles for Use by the Police and Fire Departments",
    "0455 - For the Maintenance, Use, Benefit, and Enhancement of Emergency Response Vehicles",
    "0521 - Maintenance and Construction",
    "0526 - For the Maintenance, Use, Benefit, or Enhancement of Fire Stations and Training Facilities",
    "0540 - Construction of Buildings and Other Structures",
    "0700 - Contingencies",
    "0801 - Indirect Costs",
    "0902 - For Interest on Bonds",
    "0905 - For Payment to Metropolitan Sanitary District for Wastewater Services",
    "0912 - For Payment of Bonds",
    "0931 - For the Payment of Tort and Non-Tort Judgments, Outside Counsel Expenses and Expert Costs, as Approved by the Corporation Counsel",
    "0934 - Claims for Damages and Liabilities Against the City When Ordered Paid by the City Council",
    "0937 - For Cost and Administration of Hospital and Medical Expenses for Employees Injured on Duty Who Are Not Covered Under Workers' Compensation Act",
    "0943 - For Interest on Loans",
    "0944 - For Payment on Loans",
    "0955 - Interest on Library Financing",
    "0958 - For Payment of Water Pipe Extension Certificates",
    "0959 - For Bond Fees and Costs",
    "0960 - For Loss in Collection of Taxes",
    "0961 - For Payment of Term Notes",
    "0976 - For the City's Contribution to Employees' Annuity and Benefit Fund",
    "0982 - For Expense in Connection with Recognition and Awards to Citizens of Chicago for Acts of Heroism. To Be Expended on Order of the City Council",
    "0989 - For Refunds for Cancelled Voucher Warrants and Payroll Checks and for Refunding Duplicate Payments and Payments Made in Error",
    "0991 - To Provide for Matching and Supplementary Grant Funds Currently in Effect as Well as New Grants",
    "0992 - Tow Storage Refunds",
    "0999 - To Provide for Cultural Programming and Development Grants",
    "9005 - LEGAL FEES - COMMITTEE ON FINANCE",
    "9006 - For Legal Assistance to the City Council. To Be Expended at the Direction of the Chairman of the Committee on Finance",
    "9008 - ALDERMANIC EXPENSE ALLOWENCE",
    "9010 - FINANCE COMM PROF SERVICES",
    "9027 - For the City Contribution to Social Security Tax",
    "9046 - For Operations and Maintenance Reserve",
    "9047 - For Special Capital Projects Requiring Airline Approval, Excluding Airline Improvement Program",
    "9067 - For Physical Exams",
    "9072 - CITY COUNCIL CONTINGENT AND OTHER EXPENSES",
    "9076 - City's Contribution to Medicare Tax",
    "9097 - For Capital Construction",
    "9102 - Special Programs Costs",
    "9103 - Rehabilitation Loans and Grants",
    "9110 - Property Management, Maintenance and Security",
    "9112 - Property Maintenance Contract for the Harold Washington Library Center",
    "9121 - For Payment of Costs Associated with Lobbyist Activities on Behalf of the City of Chicago",
    "9142 - Returning Citizens Initiatives",
    "9143 - Workforce Services for Target Populations",
    "9148 - To Provide for Senior Citizens - Rebate of Sewer Services When Senior Occupies Multi-Family Residency or Condominium",
    "9160 - For Expenses Related to Services Provided by PBC",
    "9180 - For World Business Chicago Program",
    "9188 - For Expenses Related to the Operation of Millennium Park",
    "9189 - For Payment of the Annual Contribution to the Chicago Transit Authority (CTA)",
    "9199 - For Purchase of Chicago Public Library Books and Materials",
    "9204 - Youth Mentoring Programs",
    "9205 - For Distribution of the Net Proceeds of the Real Property Transfer Tax - CTA Portion",
    "9211 - SINGLE-FAMILY TROUBLED BUILDING INITIATIVE",
    "9212 - MULTI-FAMILY TROUBLED BUILDING INITIATIVE",
    "9213 - Affordable Housing Density Program",
    "9219 - Implementation of Cultural Plan",
    "9222 - Emergency Medical Transportation",
    "9224 - Micro Market Recovery Program",
    "9225 - Arts and Cultural Initiatives",
    "9241 - Criminal Justice Initiatives",
    "9253 - Early Childhood Education Program",
    "9254 - Violence Reduction Program",
    "9255 - Homeless Services for Youth",
    "9259 - Youth Employment",
    "9260 - After School Programs",
    "9261 - Children's Advocacy Center",
    "9262 - Earned Income Tax Credit",
    "9263 - Homeless Services",
    "9267 - Flexible Housing Pool",
    "9283 - CARE Pilot Program",
    "9287 - For Other Maintenance, Use, and Benefits for the Chicago Fire Department (CFD)",
    "9288 - For Expenses Related to Programming for Millennium Park",
    "9291 - Legal Protection Fund",
    "9295 - Consent Decree",
    "9296 - Reproductive Health Initiative",
    "9299 - Gender Based Violence Services",
    "9333 - Less Corporate Fund Savings",
    "9438 - For Services Provided by the Department of Fleet and Facilities Management",
    "9441 - For Services Provided by the Chicago Department of Public Health",
    "9454 - For Services Provided by the Department of Planning and Development",
    "9470 - For Services Provided by Business Affairs and Consumer Protection",
    "9481 - For Services Provided by the Department of Streets and Sanitation",
    "9484 - For Services Provided by the Chicago Department of Transportation",
    "9610 - To Reimburse Corporate Fund for Pension Payments",
    "9611 - To Reimburse the Corporate Fund for Indirect Costs Chargeable to Fund",
    "9635 - To Reimburse Midway Fund for Fire Department Salaries",
    "9636 - To Reimburse Midway Fund for Fire Department Benefits",
    "9640 - To Reimburse Corporate Fund for Costs Incurred for Collection of the Real Property Transfer Tax - CTA Portion",
    "9645 - To Reimburse the Corporate Fund for Indirect Pension Costs Chargeable to Fund",
    "9646 - American Rescue Plan Revenue Replacement",
    "9647 - Transfers Out",
    "9711 - Transfer to O'Hare Fund for Administrative Salaries",
    "9713 - Transfer to Specified Operating Funds for Administration",
    "9765 - Transfer for Contractual Services",
    "9771 - Transfer for Services Provided by the Department of Assets, Information, and Services",
    "9773 - Transfer for Services Provided by the Department of Police",
    "9774 - Transfer for Services Provided by the Office of Emergency Management and Communication",
    "9775 - Transfer for Services Provided by the Fire Department",
    "9776 - Transfer for Services Provided by the Department of Streets and Sanitation",
    "9778 - Transfer for Services Provided by the Chicago Department of Aviation",
    "9803 - For Programming and Marketing",
    "9805 - For Festival Production",
    "9807 - For Redemption Expenses",
    "9813 - For Local Promotions and Marketing",
    "9980 - Municipal Fund Pension Allocation",
    "9981 - Laborers' Fund Pension Allocation",
    "9982 - Policemen's Fund Pension Allocation",
    "9983 - Firemen's Fund Pension Allocation",
    "9984 - Municipal Fund Advance Pension Payment",
    "9985 - Laborers' Fund Advance Pension Payment",
    "9986 - Policemen's Fund Advance Pension Payment",
    "9987 - Firemen's Fund Advance Pension Payment",
    "N/A - Restoration Committee",
]

fundsCodes = [
    "0B09 - CTA Real Property Transfer Tax Fund",
    "0B21 - Tax Increment Financing Administration Fund",
    "0B25 - Chicago Police CTA Detail Fund",
    "0B26 - Chicago Parking Meters Fund",
    "0B32 - Garbage Collection Fund",
    "0B42 - Foreign Fire Insurance Tax Fund",
    "0B53 - Wheelchair Accessible Vehicle Fund",
    "0B64 - Cable Local Origination Fund",
    "0B67 - Protecting CARE Fund",
    "0B70 - Cannabis Regulation Tax",
    "0B89 - Opioid Settlement Fund",
    "0B90 - Vaping Settlement Fund",
    "0B92 - Construction and Demolition Debris Management Fund",
    "0B93 - Houseshare Surcharge - Homeless Services Fund",
    "0B94 - Houseshare Surcharge - Domestic Violence Fund",
    "0D43 - Neighborhoods Opportunity Fund",
    "0D44 - Citywide Adopt-a-landmark Fund",
    "0D45 - Local Impact Fund",
    "925C - COVID-19 Grant Fund",
    "925D - Disaster Recovery Fund",
    "925E - Entitlement Fund",
    "925F - Federal Grant Fund",
    "925L - Local Public and Private Grant Fund",
    "925P - Program Income Fund",
    "925S - State Grant Fund",
    "0075 - Grants Management Fund",
    "0100 - Corporate Fund",
    "0200 - Water Fund",
    "0300 - Vehicle Tax Fund",
    "0310 - Motor Fuel Tax Fund",
    "0314 - Sewer Fund",
    "0346 - Library Fund",
    "0353 - Emergency Communication Fund",
    "0355 - Special Events and Municipal Hotel Operators' Occupation Tax Fund",
    "0510 - Bond Redemption and Interest Series Fund",
    "0521 - Library Property Tax Levy Fund",
    "0610 - Chicago Midway Airport Fund",
    "0681 - Municipal Employees' Annuity and Benefit Fund",
    "0682 - Laborers' and Retirement Board Annuity and Benefit Fund",
    "0683 - Policemen's Annuity and Benefit Fund",
    "0684 - Firemen's Annuity and Benefit Fund",
    "0740 - O'HARE REVENUE FUND",
    "0994 - Controlled Substances Fund",
    "0996 - Affordable Housing Opportunity Fund",
    "GA00 - Coronavirus Local Fiscal Recovery Fund",
]

In [3]:
## helper consts
years = list(range(2011, 2027))

normalizedColumns = [
    "fund_type",
    "fund_description",
    "department_description",
    "appropriation_authority_description",
    "appropriation_account_description",
]

replacements = [
    ["'S", "'s"],
    [" Of ", " of "],
    [" On ", " on "],
    [" The ", " the "],
    [" And ", " and "],
    [" For ", " for "],
    [" With ", " with "],
]

## helper functions
def getRowAmount(row):
    if not pd.isna(row["_ordinance_amount_"]):
        return row["_ordinance_amount_"]
    elif not pd.isna(row["appropriation_ordinance"]):
        return row["appropriation_ordinance"]
    else:
        return row["amount"]

def fmtCode(code, length, withInt=False):
    if isinstance(code, float) and math.isnan(code):
        return "NA"
    if withInt:
        if isinstance(code, str) and not code.isdigit():
            return code
        return "0" * (length - len(str(int(code)))) + str(int(code))
    return "0" * (length - len(str(code))) + str(code)

def getValues(df, x):
    subset = df[
        (df["department_number"] == x["department_number"])
        & (df["fund_code"] == x["fund_code"])
        & (df["appropriation_account"] == x["appropriation_account"])
        & (df["appropriation_authority"] == x["appropriation_authority"])
    ]
    values = subset[["amount"]].T
    values.columns = subset["year"].tolist()
    return values.T["amount"]

def cleanTitle(row):
    row = row.title()
    for replacement in replacements:
        row = row.replace(*replacement)
    return row

def makeSeries(ls, columns, titleCase=False):
    df = pd.DataFrame(ls).sort_values(by=[0])
    df.columns = columns
    df = df.set_index(columns[0])
    series = df[columns[1]]

    if titleCase:
        series = series.apply(cleanTitle)
    return series

def splitSeries(ls, columns, titleCase=False):
    return makeSeries(list(map(lambda x: x.split(" - ", 1), ls)), columns, titleCase)

def makeCSV(dfOrSeries, name):
    dfOrSeries.to_csv(f"./python/labeled/{name}.csv")
    dfOrSeries.to_csv(f"./page/data/{name}.csv")

In [4]:
df = pd.DataFrame()

for year in years:
    dfYear = pd.read_csv(f"../data/{year}-ordinance.csv")
    dfYear["year"] = year
    df = pd.concat([df, dfYear], ignore_index=True)

# clean rows and columns
df["amount"] = df.apply(getRowAmount, axis=1)
df["fund_code"] = df["fund_code"].apply(lambda x: fmtCode(x, 4))
df["department_number"] = df["department_number"].apply(lambda x: fmtCode(x, 2))
df["appropriation_account"] = df["appropriation_account"].apply(lambda x: fmtCode(x, 4))
df["appropriation_authority"] = df["appropriation_authority"].apply(lambda x: fmtCode(x, 4, True))

for colName in normalizedColumns:
    df[colName] = df[colName].str.upper()

df.head()

,fund_type,fund_code,fund_description,department_number,department,department_description,appropriation_authority,appropriation_authority_description,appropriation_account,appropriation_account_description,amount,year,_ordinance_amount_,appropriation_ordinance
0,LOCAL,0100,CORPORATE FUND,55,PB,POLICE BOARD,2005,2005 - POLICE BOARD,0050,STIPENDS,145000.00,2011,NaN,NaN
1,LOCAL,0100,CORPORATE FUND,55,PB,POLICE BOARD,2005,2005 - POLICE BOARD,0130,POSTAGE,300.00,2011,NaN,NaN
2,LOCAL,0100,CORPORATE FUND,39,BOEC,BOARD OF ELECTION COMMISSIONER,2005,2005 - ELECTION AND ADMIN DIVISION,0005,SALARIES AND WAGES - ON PAYROLL,6831849.00,2011,NaN,NaN
3,LOCAL,0100,CORPORATE FUND,39,BOEC,BOARD OF ELECTION COMMISSIONER,2005,2005 - ELECTION AND ADMIN DIVISION,0015,SCHEDULE SALARY ADJ,27342.00,2011,NaN,NaN
4,LOCAL,0100,CORPORATE FUND,39,BOEC,BOARD OF ELECTION COMMISSIONER,2005,2005 - ELECTION AND ADMIN DIVISION,0030,LESS SALARY SAVINGS FROM UNPAID TIME OFF,-607288.00,2011,NaN,NaN

In [5]:
categoryMatches = []
for key, value in categories.items():
    for code in value:
        categoryMatches.append([code, key])

categorySeries = makeSeries(categoryMatches, ["deptNum", "category"])
deptNameSeries = splitSeries(depts, ["deptNum", "deptName"], True)

deptsDF = pd.concat([deptNameSeries, categorySeries], axis=1)
deptsDF.head()

                                deptName                  category
deptNum
01                   Office of the Mayor  Finance & Administration
03       Office of the Inspector General                Regulatory
05                 Budget and Management  Finance & Administration
06             Technology and Innovation  Finance & Administration
15                          City Council   Legislative & Elections

In [14]:
accountsSeries = splitSeries(accounts, ["accountNum", "accountName"])
fundsSeries = splitSeries(fundsCodes, ["fundNum", "fundName"])
fundTypes = (
    df[["fund_type", "fund_code"]]
    .value_counts()
    .to_frame()
    .drop(["count"], axis=1)
    .reset_index()
    .sort_values(by=["fund_code"])
    .set_index("fund_code")
)

fundsDF = pd.concat([fundsSeries, fundTypes], axis=1)
fundsDF

,fundName,fund_type
0075,Grants Management Fund,GRANTS
0100,Corporate Fund,LOCAL
0200,Water Fund,LOCAL
0300,Vehicle Tax Fund,LOCAL
0310,Motor Fuel Tax Fund,LOCAL
0314,Sewer Fund,LOCAL
0346,Library Fund,LOCAL
0353,Emergency Communication Fund,LOCAL
0355,Special Events and Municipal Hotel Operators' Occupation Tax Fund,LOCAL
0510,Bond Redemption and Interest Series Fund,LOCAL
0521,Library Property Tax Levy Fund,LOCAL
0610,Chicago Midway Airport Fund,LOCAL
0681,Municipal Employees' Annuity and Benefit Fund,LOCAL
0682,Laborers' and Retirement Board Annuity and Benefit Fund,LOCAL
0683,Policemen's Annuity and Benefit Fund,LOCAL
0684,Firemen's Annuity and Benefit Fund,LOCAL
0740,O'HARE REVENUE FUND,LOCAL
0994,Controlled Substances Fund,LOCAL
0996,Affordable Housing Opportunity Fund,LOCAL
0B09,CTA Real Property Transfer Tax Fund,LOCAL
0B21,Tax Increment Financing Administration Fund,LOCAL
0B25,Chicago Police CTA Detail Fund,LOCAL
0B26,Chicago Parking Meters Fund,LOCAL
0B32,Garbage Collection Fund,LOCAL
0B42,Foreign Fire Insurance Tax Fund,LOCAL
0B53,Wheelchair Accessible Vehicle Fund,LOCAL
0B64,Cable Local Origination Fund,LOCAL
0B67,Protecting CARE Fund,LOCAL
0B70,Cannabis Regulation Tax,LOCAL
0B89,Opioid Settlement Fund,LOCAL
0B90,Vaping Settlement Fund,LOCAL
0B92,Construction and Demolition Debris Management Fund,LOCAL
0B93,Houseshare Surcharge - Homeless Services Fund,LOCAL
0B94,Houseshare Surcharge - Domestic Violence Fund,LOCAL
0D43,Neighborhoods Opportunity Fund,LOCAL
0D44,Citywide Adopt-a-landmark Fund,LOCAL
0D45,Local Impact Fund,LOCAL
925C,COVID-19 Grant Fund,GRANTS
925D,Disaster Recovery Fund,GRANTS
925E,Entitlement Fund,GRANTS
925F,Federal Grant Fund,GRANTS
925L,Local Public and Private Grant Fund,GRANTS
925P,Program Income Fund,GRANTS
925S,State Grant Fund,GRANTS
GA00,Coronavirus Local Fiscal Recovery Fund,GRANTS
0006,NaN,GRANTS
0011,NaN,GRANTS
0017,NaN,GRANTS
001C,NaN,GRANTS
0020,NaN,GRANTS
0023,NaN,GRANTS
0027,NaN,GRANTS
002C,NaN,GRANTS
003C,NaN,GRANTS
0045,NaN,GRANTS
004C,NaN,GRANTS
0050,NaN,GRANTS
005C,NaN,GRANTS
0064,NaN,GRANTS
0065,NaN,GRANTS
0066,NaN,GRANTS
006C,NaN,GRANTS
0071,NaN,GRANTS
0074,NaN,GRANTS
0079,NaN,GRANTS
008C,NaN,GRANTS
0093,NaN,GRANTS
0094,NaN,GRANTS
0096,NaN,GRANTS
009C,NaN,GRANTS
010C,NaN,GRANTS
012C,NaN,GRANTS
0168,NaN,GRANTS
0191,NaN,GRANTS
020C,NaN,GRANTS
0213,NaN,GRANTS
021C,NaN,GRANTS
0226,NaN,GRANTS
022C,NaN,GRANTS
0238,NaN,GRANTS
023C,NaN,GRANTS
0243,NaN,GRANTS
0248,NaN,GRANTS
024C,NaN,GRANTS
025C,NaN,GRANTS
0260,NaN,GRANTS
0261,NaN,GRANTS
0262,NaN,GRANTS
0263,NaN,GRANTS
0266,NaN,GRANTS
0267,NaN,GRANTS
0272,NaN,GRANTS
0277,NaN,GRANTS
0283,NaN,GRANTS
028C,NaN,GRANTS
0293,NaN,GRANTS
0298,NaN,GRANTS
0315,NaN,GRANTS
033C,NaN,GRANTS
0342,NaN,LOCAL
034C,NaN,GRANTS
0352,NaN,GRANTS
036C,NaN,GRANTS
0382,NaN,GRANTS
0383,NaN,LOCAL
0385,NaN,GRANTS
039C,NaN,GRANTS
040C,NaN,GRANTS
042C,NaN,GRANTS
044C,NaN,GRANTS
045C,NaN,GRANTS
046C,NaN,GRANTS
047C,NaN,GRANTS
048C,NaN,GRANTS
049C,NaN,GRANTS
0505,NaN,LOCAL
0509,NaN,LOCAL
050C,NaN,GRANTS
0516,NaN,LOCAL
0517,NaN,GRANTS
0525,NaN,LOCAL
0529,NaN,GRANTS
052C,NaN,GRANTS
053C,NaN,GRANTS
0549,NaN,LOCAL
054C,NaN,GRANTS
055C,NaN,GRANTS
0562,NaN,GRANTS
0563,NaN,GRANTS
0565,NaN,GRANTS
0566,NaN,GRANTS
0567,NaN,GRANTS
0578,NaN,GRANTS
0584,NaN,GRANTS
0585,NaN,GRANTS
0589,NaN,GRANTS
0594,NaN,GRANTS
0595,NaN,GRANTS
0596,NaN,GRANTS
0597,NaN,GRANTS
0598,NaN,GRANTS
0599,NaN,GRANTS
0600,NaN,GRANTS
0623,NaN,GRANTS
0624,NaN,GRANTS
0636,NaN,GRANTS
0648,NaN,GRANTS
0657,NaN,GRANTS
0674,NaN,GRANTS
0702,NaN,GRANTS
0716,NaN,GRANTS
0724,NaN,GRANTS
0764,NaN,GRANTS
0770,NaN,GRANTS
0772,NaN,GRANTS
0774,NaN,GRANTS
0781,NaN,GRANTS
0783,NaN,GRANTS
0784,NaN,GRANTS
0790,NaN,GRANTS
0792,NaN,GRANTS
0799,NaN,GRANTS
0808,NaN,GRANTS
0815,NaN,GRANTS
0816,NaN,GRANTS
0817,NaN,GRANTS
0819,NaN,GRANTS
0821,NaN,GRANTS
0824,NaN,GRANTS
0825,NaN,GRANTS
0827,NaN,GRANTS
0831,NaN,GRANTS
0833,NaN,GRANTS
0834,NaN,GRANTS
0842,NaN,GRANTS
0845,NaN,GRANTS
0847,NaN,GRANTS
0848,NaN,GRANTS
0851,NaN,GRANTS
0863,NaN,GRANTS
0865,NaN,GRANTS
0866,NaN,GRANTS
0868,NaN,GRANTS
0869,NaN,GRANTS
0877,NaN,GRANTS
0878,NaN,GRANTS
0880,NaN,GRANTS
0884,NaN,GRANTS
0889,NaN,GRANTS
0890,NaN,GRANTS
0896,NaN,GRANTS
0898,NaN,GRANTS
0902,NaN,GRANTS
0929,NaN,GRANTS
0934,NaN,LOCAL
0995,NaN,LOCAL
0B05,NaN,GRANTS
0B17,NaN,GRANTS
0B39,NaN,LOCAL
0B40,NaN,LOCAL
0B41,NaN,LOCAL
0B43,NaN,LOCAL
0B82,NaN,LOCAL
0G01,NaN,GRANTS
0H01,NaN,GRANTS
0H04,NaN,GRANTS
0H05,NaN,GRANTS
0H06,NaN,GRANTS
0H07,NaN,GRANTS
0H08,NaN,GRANTS
0H09,NaN,GRANTS
0H11,NaN,GRANTS
0H12,NaN,GRANTS
0H13,NaN,GRANTS
0H14,NaN,GRANTS
0H15,NaN,GRANTS
0H16,NaN,GRANTS
0H18,NaN,GRANTS
0H19,NaN,GRANTS
0H20,NaN,GRANTS
0H21,NaN,GRANTS
0H22,NaN,GRANTS
0H23,NaN,GRANTS
0H24,NaN,GRANTS
0H25,NaN,GRANTS
0H26,NaN,GRANTS
0H27,NaN,GRANTS
0H28,NaN,GRANTS
0H29,NaN,GRANTS
0H30,NaN,GRANTS
0H31,NaN,GRANTS
0H32,NaN,GRANTS
0H33,NaN,GRANTS
0H34,NaN,GRANTS
0H35,NaN,GRANTS
0H36,NaN,GRANTS
0H37,NaN,GRANTS
0H38,NaN,GRANTS
0H39,NaN,GRANTS
0H40,NaN,GRANTS
0H41,NaN,GRANTS
0H42,NaN,GRANTS
0H43,NaN,GRANTS
0H44,NaN,GRANTS
0H45,NaN,GRANTS
0H46,NaN,GRANTS
0H47,NaN,GRANTS
0H49,NaN,GRANTS
0H50,NaN,GRANTS
0H51,NaN,GRANTS
0H52,NaN,GRANTS
0H53,NaN,GRANTS
0H54,NaN,GRANTS
0H55,NaN,GRANTS
0H56,NaN,GRANTS
0H57,NaN,GRANTS
0H58,NaN,GRANTS
0H59,NaN,GRANTS
0H60,NaN,GRANTS
0H61,NaN,GRANTS
0H62,NaN,GRANTS
0H63,NaN,GRANTS
0H64,NaN,GRANTS
0H65,NaN,GRANTS
0H67,NaN,GRANTS
0H68,NaN,GRANTS
0H69,NaN,GRANTS
0H70,NaN,GRANTS
0H71,NaN,GRANTS
0H72,NaN,GRANTS
0H73,NaN,GRANTS
0H74,NaN,GRANTS
0H75,NaN,GRANTS
0H76,NaN,GRANTS
0H77,NaN,GRANTS
0H78,NaN,GRANTS
0H79,NaN,GRANTS
0H80,NaN,GRANTS
0H81,NaN,GRANTS
0H82,NaN,GRANTS
0H83,NaN,GRANTS
0H84,NaN,GRANTS
0H85,NaN,GRANTS
0H86,NaN,GRANTS
0H88,NaN,GRANTS
0H89,NaN,GRANTS
0H90,NaN,GRANTS
0H91,NaN,GRANTS
0H92,NaN,GRANTS
0H93,NaN,GRANTS
0H94,NaN,GRANTS
0H96,NaN,GRANTS
0H97,NaN,GRANTS
0H99,NaN,GRANTS
0J01,NaN,GRANTS
0J02,NaN,GRANTS
0J03,NaN,GRANTS
0J04,NaN,GRANTS
0J05,NaN,GRANTS
0J06,NaN,GRANTS
0J07,NaN,GRANTS
0J08,NaN,GRANTS
0J09,NaN,GRANTS
0J11,NaN,GRANTS
0J12,NaN,GRANTS
0J13,NaN,GRANTS
0J14,NaN,GRANTS
0J16,NaN,GRANTS
0J18,NaN,GRANTS
0J19,NaN,GRANTS
0J20,NaN,GRANTS
0J21,NaN,GRANTS
0J22,NaN,GRANTS
0J23,NaN,GRANTS
0J24,NaN,GRANTS
0J25,NaN,GRANTS
0J26,NaN,GRANTS
0J28,NaN,GRANTS
0J30,NaN,GRANTS
0J31,NaN,GRANTS
0J32,NaN,GRANTS
0J38,NaN,GRANTS
0J39,NaN,GRANTS
0J40,NaN,GRANTS
0J41,NaN,CDBG
0J42,NaN,CDBG
0J43,NaN,CDBG
0J44,NaN,CDBG
0J45,NaN,CDBG
0J46,NaN,CDBG
0J47,NaN,CDBG
0J48,NaN,CDBG
0J49,NaN,CDBG
0J50,NaN,CDBG
0J51,NaN,GRANTS
0J52,NaN,GRANTS
0J53,NaN,GRANTS
0J54,NaN,GRANTS
0J55,NaN,GRANTS
0J56,NaN,GRANTS
0J57,NaN,GRANTS
0J59,NaN,GRANTS
0J62,NaN,GRANTS
0J63,NaN,GRANTS
0J64,NaN,GRANTS
0J65,NaN,GRANTS
0J66,NaN,GRANTS
0J67,NaN,GRANTS
0J68,NaN,GRANTS
0J69,NaN,GRANTS
0J70,NaN,GRANTS
0J74,NaN,GRANTS
0J75,NaN,GRANTS
0J76,NaN,GRANTS
0J77,NaN,GRANTS
0J78,NaN,GRANTS
0J79,NaN,GRANTS
0J80,NaN,GRANTS
0J81,NaN,GRANTS
0J83,NaN,GRANTS
0J84,NaN,GRANTS
0J85,NaN,GRANTS
0J86,NaN,GRANTS
0J87,NaN,GRANTS
0J89,NaN,GRANTS
0J92,NaN,GRANTS
0J94,NaN,GRANTS
0J95,NaN,GRANTS
0J96,NaN,GRANTS
0J97,NaN,GRANTS
0J98,NaN,GRANTS
0J99,NaN,GRANTS
0K03,NaN,GRANTS
0K04,NaN,GRANTS
0K06,NaN,GRANTS
0K11,NaN,GRANTS
0K14,NaN,GRANTS
0K17,NaN,GRANTS
0K20,NaN,GRANTS
0K21,NaN,GRANTS
0K23,NaN,GRANTS
0K24,NaN,GRANTS
0K25,NaN,GRANTS
0K26,NaN,GRANTS
0K27,NaN,GRANTS
0K28,NaN,GRANTS
0K30,NaN,GRANTS
0K31,NaN,GRANTS
0K32,NaN,GRANTS
0K37,NaN,CDBG
0K38,NaN,CDBG
0K39,NaN,CDBG
0K40,NaN,CDBG
0K41,NaN,GRANTS
0K43,NaN,GRANTS
0K44,NaN,GRANTS
0K45,NaN,GRANTS
0K46,NaN,GRANTS
0K47,NaN,GRANTS
0K48,NaN,GRANTS
0K49,NaN,GRANTS
0K50,NaN,GRANTS
0K51,NaN,GRANTS
0K52,NaN,GRANTS
0K54,NaN,GRANTS
0K55,NaN,GRANTS
0K57,NaN,GRANTS
0K58,NaN,GRANTS
0K59,NaN,GRANTS
0K60,NaN,GRANTS
0K61,NaN,GRANTS
0K62,NaN,GRANTS
0K63,NaN,GRANTS
0K64,NaN,GRANTS
0K65,NaN,GRANTS
0K66,NaN,GRANTS
0K67,NaN,GRANTS
0K68,NaN,GRANTS
0K69,NaN,GRANTS
0K70,NaN,GRANTS
0K72,NaN,GRANTS
0K73,NaN,GRANTS
0K75,NaN,GRANTS
0K76,NaN,GRANTS
0K77,NaN,GRANTS
0K78,NaN,GRANTS
0K79,NaN,GRANTS
0K80,NaN,GRANTS
0K83,NaN,GRANTS
0K85,NaN,GRANTS
0K86,NaN,GRANTS
0K87,NaN,GRANTS
0K89,NaN,GRANTS
0K91,NaN,GRANTS
0K93,NaN,GRANTS
0K94,NaN,GRANTS
0K95,NaN,GRANTS
0K98,NaN,GRANTS
0K99,NaN,GRANTS
0L00,NaN,GRANTS
0L01,NaN,GRANTS
0L03,NaN,GRANTS
0L04,NaN,GRANTS
0L05,NaN,GRANTS
0L06,NaN,GRANTS
0L07,NaN,GRANTS
0L08,NaN,GRANTS
0L09,NaN,GRANTS
0L10,NaN,GRANTS
0L13,NaN,GRANTS
0L14,NaN,GRANTS
0L18,NaN,GRANTS
0L19,NaN,GRANTS
0L22,NaN,GRANTS
0L23,NaN,GRANTS
0L26,NaN,GRANTS
0L29,NaN,GRANTS
0L32,NaN,GRANTS
0L33,NaN,GRANTS
0L34,NaN,GRANTS
0L35,NaN,GRANTS
0L36,NaN,GRANTS
0L37,NaN,GRANTS
0L38,NaN,GRANTS
0L39,NaN,GRANTS
0L40,NaN,GRANTS
0L41,NaN,GRANTS
0L42,NaN,GRANTS
0L43,NaN,GRANTS
0L44,NaN,GRANTS
0L46,NaN,GRANTS
0L47,NaN,GRANTS
0L48,NaN,GRANTS
0L49,NaN,GRANTS
0L50,NaN,GRANTS
0L52,NaN,GRANTS
0L60,NaN,GRANTS
0L64,NaN,GRANTS
0L69,NaN,GRANTS
0L71,NaN,GRANTS
0L72,NaN,GRANTS
0L73,NaN,GRANTS
0L74,NaN,GRANTS
0L75,NaN,GRANTS
0L76,NaN,GRANTS
0L77,NaN,GRANTS
0L78,NaN,GRANTS
0L79,NaN,GRANTS
0L80,NaN,GRANTS
0L81,NaN,GRANTS
0L82,NaN,GRANTS
0L83,NaN,GRANTS
0L84,NaN,GRANTS
0L85,NaN,GRANTS
0L86,NaN,GRANTS
0L87,NaN,GRANTS
0L89,NaN,GRANTS
0L90,NaN,GRANTS
0L91,NaN,GRANTS
0L93,NaN,GRANTS
0L94,NaN,GRANTS
0L98,NaN,GRANTS
0L99,NaN,GRANTS
0M01,NaN,GRANTS
0M02,NaN,GRANTS
0M04,NaN,GRANTS
0M05,NaN,GRANTS
0M06,NaN,GRANTS
0M07,NaN,GRANTS
0M08,NaN,GRANTS
0M09,NaN,GRANTS
0M11,NaN,GRANTS
0M13,NaN,GRANTS
0M14,NaN,GRANTS
0M22,NaN,GRANTS
0M27,NaN,GRANTS
0M28,NaN,GRANTS
0M29,NaN,GRANTS
0M35,NaN,GRANTS
0M39,NaN,GRANTS
0M46,NaN,GRANTS
0M47,NaN,GRANTS
0M48,NaN,GRANTS
0M49,NaN,GRANTS
0M51,NaN,GRANTS
0M52,NaN,GRANTS
0M53,NaN,GRANTS
0M54,NaN,GRANTS
0M55,NaN,GRANTS
0M56,NaN,GRANTS
0M57,NaN,GRANTS
0M58,NaN,GRANTS
0M59,NaN,GRANTS
0M60,NaN,GRANTS
0M61,NaN,GRANTS
0M62,NaN,GRANTS
0M64,NaN,GRANTS
0M65,NaN,GRANTS
0M66,NaN,GRANTS
0M67,NaN,GRANTS
0M69,NaN,GRANTS
0M72,NaN,GRANTS
0M73,NaN,GRANTS
0M83,NaN,GRANTS
0M84,NaN,GRANTS
0M85,NaN,GRANTS
0M86,NaN,GRANTS
0M87,NaN,GRANTS
0M88,NaN,GRANTS
0M91,NaN,GRANTS
0M92,NaN,GRANTS
0M93,NaN,GRANTS
0M95,NaN,GRANTS
0N00,NaN,GRANTS
0N01,NaN,GRANTS
0N02,NaN,GRANTS
0N03,NaN,GRANTS
0N09,NaN,GRANTS
0N10,NaN,GRANTS
0N12,NaN,GRANTS
0N13,NaN,GRANTS
0N14,NaN,GRANTS
0N15,NaN,GRANTS
0N16,NaN,GRANTS
0N17,NaN,GRANTS
0N19,NaN,GRANTS
0N20,NaN,GRANTS
0N21,NaN,GRANTS
0N22,NaN,GRANTS
0N23,NaN,GRANTS
0N24,NaN,GRANTS
0N25,NaN,GRANTS
0N26,NaN,GRANTS
0N27,NaN,GRANTS
0N28,NaN,GRANTS
0N29,NaN,GRANTS
0N30,NaN,GRANTS
0N31,NaN,GRANTS
0N32,NaN,GRANTS
0N33,NaN,GRANTS
0N34,NaN,GRANTS
0N35,NaN,GRANTS
0N36,NaN,GRANTS
0N37,NaN,GRANTS
0N39,NaN,GRANTS
0N40,NaN,GRANTS
0N42,NaN,GRANTS
0N44,NaN,GRANTS
0N45,NaN,GRANTS
0N46,NaN,GRANTS
0N47,NaN,GRANTS
0N48,NaN,GRANTS
0N49,NaN,GRANTS
0N51,NaN,GRANTS
0N52,NaN,GRANTS
0N53,NaN,GRANTS
0N54,NaN,GRANTS
0N55,NaN,GRANTS
0N56,NaN,GRANTS
0N58,NaN,GRANTS
0N59,NaN,GRANTS
0N60,NaN,GRANTS
0N61,NaN,GRANTS
0N62,NaN,GRANTS
0N63,NaN,GRANTS
0N64,NaN,GRANTS
0N65,NaN,GRANTS
0N66,NaN,GRANTS
0N67,NaN,GRANTS
0N69,NaN,GRANTS
0N70,NaN,GRANTS
0N74,NaN,GRANTS
0N78,NaN,GRANTS
0N80,NaN,GRANTS
0N81,NaN,GRANTS
0N84,NaN,GRANTS
0N88,NaN,GRANTS
0N89,NaN,GRANTS
0N90,NaN,GRANTS
0N91,NaN,GRANTS
0N92,NaN,GRANTS
0N93,NaN,GRANTS
0N94,NaN,GRANTS
0N95,NaN,GRANTS
0N96,NaN,GRANTS
0N97,NaN,GRANTS
0N98,NaN,GRANTS
0N99,NaN,GRANTS
0P04,NaN,GRANTS
0P07,NaN,GRANTS
0P11,NaN,GRANTS
0P12,NaN,GRANTS
0P14,NaN,GRANTS
0P16,NaN,GRANTS
0P17,NaN,GRANTS
0P18,NaN,GRANTS
0P19,NaN,GRANTS
0P20,NaN,GRANTS
0P21,NaN,GRANTS
0P23,NaN,GRANTS
0P27,NaN,GRANTS
0P28,NaN,GRANTS
0P29,NaN,GRANTS
0P30,NaN,GRANTS
0P31,NaN,GRANTS
0P33,NaN,GRANTS
0P36,NaN,GRANTS
0P37,NaN,GRANTS
0P38,NaN,GRANTS
0P39,NaN,GRANTS
0P40,NaN,GRANTS
0P41,NaN,GRANTS
0P42,NaN,GRANTS
0P46,NaN,GRANTS
0P47,NaN,GRANTS
0P49,NaN,GRANTS
0P51,NaN,GRANTS
0P52,NaN,GRANTS
0P53,NaN,GRANTS
0P55,NaN,GRANTS
0P56,NaN,GRANTS
0P58,NaN,GRANTS
0P59,NaN,GRANTS
0P60,NaN,GRANTS
0P61,NaN,GRANTS
0P62,NaN,GRANTS
0P64,NaN,GRANTS
0P65,NaN,GRANTS
0P67,NaN,GRANTS
0P68,NaN,GRANTS
0P69,NaN,GRANTS
0P71,NaN,GRANTS
0P72,NaN,GRANTS
0P73,NaN,GRANTS
0P82,NaN,GRANTS
0P83,NaN,GRANTS
0P84,NaN,GRANTS
0P87,NaN,GRANTS
0P88,NaN,GRANTS
0P92,NaN,GRANTS
0P93,NaN,GRANTS
0P94,NaN,GRANTS
0P95,NaN,GRANTS
0P96,NaN,GRANTS
0P97,NaN,GRANTS
0P98,NaN,GRANTS
0P99,NaN,GRANTS
0R11,NaN,GRANTS
0S04,NaN,GRANTS
0S06,NaN,GRANTS
0S13,NaN,GRANTS
0S15,NaN,GRANTS
0S16,NaN,GRANTS
0S21,NaN,GRANTS
0S22,NaN,GRANTS
0S26,NaN,GRANTS
0S27,NaN,GRANTS
0S29,NaN,GRANTS
0S51,NaN,GRANTS
0S54,NaN,GRANTS
0S55,NaN,GRANTS
0S56,NaN,GRANTS
0S57,NaN,GRANTS
0S60,NaN,GRANTS
0S61,NaN,GRANTS
0S62,NaN,GRANTS
0S73,NaN,GRANTS
0S80,NaN,GRANTS
0S81,NaN,GRANTS
0S82,NaN,GRANTS
0S83,NaN,GRANTS
0S84,NaN,GRANTS
0S85,NaN,GRANTS
0S87,NaN,GRANTS
0S90,NaN,GRANTS
0S93,NaN,GRANTS
0S94,NaN,GRANTS
0S95,NaN,GRANTS
0S96,NaN,GRANTS
0S97,NaN,GRANTS
0S98,NaN,GRANTS
0T00,NaN,GRANTS
0T01,NaN,GRANTS
0T03,NaN,GRANTS
0T04,NaN,GRANTS
0T05,NaN,GRANTS
0T06,NaN,GRANTS
0T07,NaN,GRANTS
0T08,NaN,GRANTS
0T09,NaN,GRANTS
0T10,NaN,GRANTS
0T11,NaN,GRANTS
0T12,NaN,GRANTS
0T13,NaN,GRANTS
0T14,NaN,GRANTS
0T15,NaN,GRANTS
0T16,NaN,GRANTS
0T17,NaN,GRANTS
0T18,NaN,GRANTS
0T19,NaN,GRANTS
0T20,NaN,GRANTS
0T23,NaN,GRANTS
0T24,NaN,GRANTS
0T28,NaN,GRANTS
0T33,NaN,GRANTS
0T34,NaN,GRANTS
0T36,NaN,GRANTS
0T37,NaN,GRANTS
0T38,NaN,GRANTS
0T39,NaN,GRANTS
0T40,NaN,GRANTS
0T41,NaN,GRANTS
0T42,NaN,GRANTS
0T44,NaN,GRANTS
0T45,NaN,GRANTS
0T46,NaN,GRANTS
0T47,NaN,GRANTS
0T48,NaN,GRANTS
0T49,NaN,GRANTS
0T50,NaN,GRANTS
0T51,NaN,GRANTS
0T52,NaN,GRANTS
0T54,NaN,GRANTS
0T55,NaN,GRANTS
0T57,NaN,GRANTS
0T58,NaN,GRANTS
0T59,NaN,GRANTS
0T60,NaN,GRANTS
0T61,NaN,GRANTS
0T62,NaN,GRANTS
0T63,NaN,GRANTS
0T64,NaN,GRANTS
0T65,NaN,GRANTS
0T66,NaN,GRANTS
0T67,NaN,GRANTS
0T68,NaN,GRANTS
0T70,NaN,GRANTS
0T71,NaN,GRANTS
0T73,NaN,GRANTS
0T74,NaN,GRANTS
0T76,NaN,GRANTS
0T77,NaN,GRANTS
0T78,NaN,GRANTS
0T79,NaN,GRANTS
0T80,NaN,GRANTS
0T81,NaN,GRANTS
0T82,NaN,GRANTS
0T83,NaN,GRANTS
0T84,NaN,GRANTS
0T85,NaN,GRANTS
0T86,NaN,GRANTS
0T87,NaN,GRANTS
0T88,NaN,GRANTS
0T89,NaN,GRANTS
0T92,NaN,GRANTS
0T95,NaN,GRANTS
0T96,NaN,GRANTS
0T98,NaN,GRANTS
0U00,NaN,GRANTS
0U01,NaN,GRANTS
0U02,NaN,GRANTS
0U07,NaN,GRANTS
0U08,NaN,GRANTS
0U09,NaN,GRANTS
0U10,NaN,GRANTS
0U11,NaN,GRANTS
0U12,NaN,GRANTS
0U13,NaN,GRANTS
0U15,NaN,GRANTS
0U16,NaN,GRANTS
0U17,NaN,GRANTS
0U19,NaN,GRANTS
0U21,NaN,GRANTS
0U22,NaN,GRANTS
0U23,NaN,GRANTS
0U25,NaN,GRANTS
0U26,NaN,GRANTS
0U27,NaN,GRANTS
0U28,NaN,GRANTS
0U29,NaN,GRANTS
0U30,NaN,GRANTS
0U31,NaN,GRANTS
0U33,NaN,GRANTS
0U34,NaN,GRANTS
0U35,NaN,GRANTS
0U36,NaN,GRANTS
0U37,NaN,GRANTS
0U38,NaN,GRANTS
0U39,NaN,GRANTS
0U40,NaN,GRANTS
0U44,NaN,GRANTS
0U45,NaN,GRANTS
0U46,NaN,GRANTS
0U49,NaN,GRANTS
0U50,NaN,GRANTS
0U51,NaN,GRANTS
0U52,NaN,GRANTS
0U53,NaN,GRANTS
0U54,NaN,GRANTS
0U55,NaN,GRANTS
0U56,NaN,GRANTS
0U57,NaN,GRANTS
0U58,NaN,GRANTS
0U59,NaN,GRANTS
0U60,NaN,GRANTS
0U61,NaN,GRANTS
0U62,NaN,GRANTS
0U64,NaN,GRANTS
0U65,NaN,GRANTS
0U66,NaN,GRANTS
0U67,NaN,GRANTS
0U68,NaN,GRANTS
0U69,NaN,GRANTS
0U70,NaN,GRANTS
0U71,NaN,GRANTS
0U72,NaN,GRANTS
0U73,NaN,GRANTS
0U74,NaN,GRANTS
0U77,NaN,GRANTS
0U78,NaN,GRANTS
0U80,NaN,GRANTS
0U81,NaN,GRANTS
0U82,NaN,GRANTS
0U83,NaN,GRANTS
0U86,NaN,GRANTS
0U88,NaN,GRANTS
0U90,NaN,GRANTS
0U91,NaN,GRANTS
0U92,NaN,GRANTS
0U93,NaN,GRANTS
0U94,NaN,GRANTS
0U95,NaN,GRANTS
0U96,NaN,GRANTS
0U97,NaN,GRANTS
0U98,NaN,GRANTS
0V00,NaN,GRANTS
0V01,NaN,GRANTS
0V02,NaN,GRANTS
0V03,NaN,GRANTS
0V05,NaN,GRANTS
0V06,NaN,GRANTS
0V07,NaN,GRANTS
0V08,NaN,GRANTS
0V09,NaN,GRANTS
0V10,NaN,GRANTS
0V12,NaN,GRANTS
0V13,NaN,GRANTS
0V14,NaN,GRANTS
0V17,NaN,GRANTS
0V18,NaN,GRANTS
0V19,NaN,GRANTS
0V20,NaN,GRANTS
0V21,NaN,GRANTS
0V22,NaN,GRANTS
0V24,NaN,GRANTS
0V25,NaN,GRANTS
0V26,NaN,GRANTS
0V27,NaN,GRANTS
0V29,NaN,GRANTS
0V30,NaN,GRANTS
0V31,NaN,GRANTS
0V33,NaN,GRANTS
0V34,NaN,GRANTS
0V35,NaN,GRANTS
0V36,NaN,GRANTS
0V37,NaN,GRANTS
0V39,NaN,GRANTS
0V40,NaN,GRANTS
0V41,NaN,GRANTS
0V42,NaN,GRANTS
0V43,NaN,GRANTS
0V44,NaN,GRANTS
0V47,NaN,GRANTS
0V48,NaN,GRANTS
0V49,NaN,GRANTS
0V50,NaN,GRANTS
0V51,NaN,GRANTS
0V52,NaN,GRANTS
0V53,NaN,GRANTS
0V54,NaN,GRANTS
0V55,NaN,GRANTS
0V56,NaN,GRANTS
0V57,NaN,GRANTS
0V58,NaN,GRANTS
0V59,NaN,GRANTS
0V61,NaN,GRANTS
0V62,NaN,GRANTS
0V63,NaN,GRANTS
0V64,NaN,GRANTS
0V65,NaN,GRANTS
0V66,NaN,GRANTS
0V67,NaN,GRANTS
0V68,NaN,GRANTS
0V69,NaN,GRANTS
0V70,NaN,GRANTS
0V71,NaN,GRANTS
0V72,NaN,GRANTS
0V73,NaN,GRANTS
0V74,NaN,GRANTS
0V75,NaN,GRANTS
0V76,NaN,GRANTS
0V80,NaN,GRANTS
0V81,NaN,GRANTS
0V82,NaN,GRANTS
0V84,NaN,GRANTS
0V85,NaN,GRANTS
0V86,NaN,GRANTS
0V87,NaN,GRANTS
0V88,NaN,GRANTS
0V89,NaN,GRANTS
0V91,NaN,GRANTS
0V93,NaN,GRANTS
0V95,NaN,GRANTS
0V97,NaN,GRANTS
0V98,NaN,GRANTS
0V99,NaN,GRANTS
0W00,NaN,GRANTS
0W01,NaN,GRANTS
0W02,NaN,GRANTS
0W03,NaN,GRANTS
0W04,NaN,GRANTS
0W05,NaN,GRANTS
0W06,NaN,GRANTS
0W11,NaN,GRANTS
0W12,NaN,GRANTS
0W13,NaN,GRANTS
0W15,NaN,GRANTS
0W16,NaN,GRANTS
0W18,NaN,GRANTS
0W20,NaN,GRANTS
0W21,NaN,GRANTS
0W22,NaN,GRANTS
0W23,NaN,GRANTS
0W24,NaN,GRANTS
0W25,NaN,GRANTS
0W27,NaN,GRANTS
0W28,NaN,GRANTS
0W29,NaN,GRANTS
0W30,NaN,GRANTS
0W32,NaN,GRANTS
0W33,NaN,GRANTS
0W38,NaN,GRANTS
0W39,NaN,GRANTS
0W43,NaN,GRANTS
0W44,NaN,GRANTS
0W45,NaN,GRANTS
0W46,NaN,GRANTS
0W48,NaN,GRANTS
0W49,NaN,GRANTS
0W50,NaN,GRANTS
0W51,NaN,GRANTS
0W52,NaN,GRANTS
0W53,NaN,GRANTS
0W54,NaN,GRANTS
0W55,NaN,GRANTS
0W56,NaN,GRANTS
0W57,NaN,GRANTS
0W59,NaN,GRANTS
0W60,NaN,GRANTS
0W63,NaN,GRANTS
0W64,NaN,GRANTS
0W65,NaN,GRANTS
0W66,NaN,GRANTS
0W68,NaN,GRANTS
0W73,NaN,GRANTS
0W74,NaN,GRANTS
0W75,NaN,GRANTS
0W76,NaN,GRANTS
0W77,NaN,GRANTS
0W78,NaN,GRANTS
0W79,NaN,GRANTS
0W81,NaN,GRANTS
0W82,NaN,GRANTS
0W84,NaN,GRANTS
0W85,NaN,GRANTS
0W87,NaN,GRANTS
0W88,NaN,GRANTS
0W90,NaN,GRANTS
0W91,NaN,GRANTS
0W92,NaN,GRANTS
0W93,NaN,GRANTS
0W94,NaN,GRANTS
0W95,NaN,GRANTS
0W96,NaN,GRANTS
0W97,NaN,GRANTS
0W99,NaN,GRANTS
0X02,NaN,GRANTS
0X03,NaN,GRANTS
0X04,NaN,GRANTS
0X05,NaN,GRANTS
0X06,NaN,GRANTS
0X09,NaN,GRANTS
0X10,NaN,GRANTS
0X11,NaN,GRANTS
0X12,NaN,GRANTS
0X13,NaN,GRANTS
0X14,NaN,GRANTS
0X15,NaN,GRANTS
0X16,NaN,GRANTS
0X18,NaN,GRANTS
0X19,NaN,GRANTS
0X20,NaN,GRANTS
0X22,NaN,GRANTS
0X23,NaN,GRANTS
0X24,NaN,GRANTS
0X25,NaN,GRANTS
0X26,NaN,GRANTS
0X27,NaN,GRANTS
0X28,NaN,GRANTS
0X29,NaN,GRANTS
0X30,NaN,GRANTS
0X31,NaN,GRANTS
0X32,NaN,GRANTS
0X33,NaN,GRANTS
0X34,NaN,GRANTS
0X35,NaN,GRANTS
0X36,NaN,GRANTS
0X37,NaN,GRANTS
0X38,NaN,GRANTS
0X39,NaN,GRANTS
0X41,NaN,GRANTS
0X42,NaN,GRANTS
0X44,NaN,GRANTS
0X45,NaN,GRANTS
0X47,NaN,GRANTS
0X49,NaN,GRANTS
0X50,NaN,GRANTS
0X52,NaN,GRANTS
0X55,NaN,GRANTS
0X56,NaN,GRANTS
0X57,NaN,GRANTS
0X59,NaN,GRANTS
0X60,NaN,GRANTS
0X61,NaN,GRANTS
0X62,NaN,GRANTS
0X63,NaN,GRANTS
0X64,NaN,GRANTS
0X65,NaN,GRANTS
0X66,NaN,GRANTS
0X67,NaN,GRANTS
0X68,NaN,GRANTS
0X69,NaN,GRANTS
0X70,NaN,GRANTS
0X71,NaN,GRANTS
0X72,NaN,GRANTS
0X73,NaN,GRANTS
0X74,NaN,GRANTS
0X75,NaN,GRANTS
0X76,NaN,GRANTS
0X77,NaN,GRANTS
0X78,NaN,GRANTS
0X79,NaN,GRANTS
0X80,NaN,GRANTS
0X81,NaN,GRANTS
0X82,NaN,GRANTS
0X83,NaN,GRANTS
0X84,NaN,GRANTS
0X85,NaN,GRANTS
0X86,NaN,GRANTS
0X87,NaN,GRANTS
0X88,NaN,GRANTS
0X89,NaN,GRANTS
0X90,NaN,GRANTS
0X92,NaN,GRANTS
0X95,NaN,GRANTS
0X96,NaN,GRANTS
0X97,NaN,GRANTS
0X98,NaN,GRANTS
0X99,NaN,GRANTS
0Y01,NaN,GRANTS
0Y02,NaN,GRANTS
0Y03,NaN,GRANTS
0Y04,NaN,GRANTS
0Y05,NaN,GRANTS
0Y06,NaN,GRANTS
0Y07,NaN,GRANTS
0Y08,NaN,GRANTS
0Y10,NaN,GRANTS
0Y11,NaN,GRANTS
0Y12,NaN,GRANTS
0Y13,NaN,GRANTS
0Y14,NaN,GRANTS
0Y15,NaN,GRANTS
0Y16,NaN,GRANTS
0Y17,NaN,GRANTS
0Y18,NaN,GRANTS
0Y19,NaN,GRANTS
0Y20,NaN,GRANTS
0Y21,NaN,GRANTS
0Y22,NaN,GRANTS
0Y23,NaN,GRANTS
0Y24,NaN,GRANTS
0Y25,NaN,GRANTS
0Y26,NaN,GRANTS
0Y27,NaN,GRANTS
0Y28,NaN,GRANTS
0Y29,NaN,GRANTS
0Y30,NaN,GRANTS
0Y31,NaN,GRANTS
0Y32,NaN,GRANTS
0Y33,NaN,GRANTS
0Y34,NaN,GRANTS
0Y35,NaN,GRANTS
0Y36,NaN,GRANTS
0Y37,NaN,GRANTS
0Y38,NaN,GRANTS
0Y39,NaN,GRANTS
0Y40,NaN,GRANTS
0Y41,NaN,GRANTS
0Y42,NaN,GRANTS
0Y43,NaN,GRANTS
0Y44,NaN,GRANTS
0Y45,NaN,GRANTS
0Y46,NaN,GRANTS
0Y47,NaN,GRANTS
0Y48,NaN,GRANTS
0Y49,NaN,GRANTS
0Y50,NaN,GRANTS
0Y51,NaN,GRANTS
0Y52,NaN,GRANTS
0Y53,NaN,GRANTS
0Y54,NaN,GRANTS
0Y55,NaN,GRANTS
0Y56,NaN,GRANTS
0Y57,NaN,GRANTS
0Y58,NaN,GRANTS
0Y59,NaN,GRANTS
0Y60,NaN,GRANTS
0Y61,NaN,GRANTS
0Y62,NaN,GRANTS
0Y63,NaN,GRANTS
0Y64,NaN,GRANTS
0Y65,NaN,GRANTS
0Y66,NaN,GRANTS
0Y67,NaN,GRANTS
0Y68,NaN,GRANTS
0Y69,NaN,GRANTS
0Y70,NaN,GRANTS
0Y71,NaN,GRANTS
0Y72,NaN,GRANTS
0Y73,NaN,GRANTS
0Y74,NaN,GRANTS

In [7]:
cleaned = (
    df[
        [
            "department_number",
            "fund_code",
            "appropriation_account",
            "appropriation_authority",
        ]
    ]
    .value_counts()
    .to_frame()
    .drop(["count"], axis=1)
    .reset_index()
    .sort_values(
        by=[
            "department_number",
            "fund_code",
            "appropriation_account",
            "appropriation_authority",
        ]
    )
)

amounts = cleaned.merge(
    cleaned.apply(lambda row: getValues(df, row), axis=1, result_type="expand").fillna(0),
    left_index=True,
    right_index=True,
)

amounts.head()

,department_number,fund_code,appropriation_account,appropriation_authority,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026
1141,01,0100,0005,2005,5892558.00,5142155.00,5366703.00,5511957.00,5550657.00,5965114.00,6279625.00,6528090.00,7028929.00,9389344.00,9235579.00,10206075.00,10514517.00,11370347.00,10692655.00,10707977.00
8339,01,0100,0030,2005,-519910.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
2524,01,0100,0039,2005,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,298400.00,149200.00,180200.00,180200.00,249060.00,260000.00,57490.00
1142,01,0100,0126,2005,1310.00,1200.00,1200.00,1200.00,1000.00,1000.00,1200.00,1200.00,1200.00,1600.00,1600.00,1600.00,1600.00,1600.00,3200.00,1500.00
1143,01,0100,0130,2005,30918.00,23400.00,18000.00,10000.00,5019.00,5693.00,5000.00,5000.00,5000.00,5500.00,5500.00,5500.00,5500.00,5500.00,1600.00,500.00

In [8]:
df[df["department_number"] == "38"][
    ["department_description", "year"]
].value_counts().to_frame().sort_values(by="year", ascending=False)

                                                      count
department_description                          year
DEPARTMENT OF FLEET AND FACILITY MANAGEMENT     2026    186
                                                2025    191
                                                2024    183
DEPARTMENT OF ASSETS  INFORMATION  AND SERVICES 2023    246
AIS                                             2022    241
                                                2021    210
DAIS                                            2020    211
FFM                                             2019    187
                                                2018    187
FLEET AND FACILITY MANAGEMENT                   2017    190
                                                2016    208
FLEET AND FACILITY MGMT                         2015    210
                                                2014    200
                                                2013    194
FLEET AND FACILITY MANAGEMENT                   2012    201
GENERAL SERVICES                                2011    125