In [1]:
# imports
import pandas as pd
import matplotlib as plt
import numpy as np
import math

# display options
pd.set_option("display.max_rows", None)
pd.set_option("display.max_colwidth", None)
pd.set_option("display.float_format", "{:.2f}".format)

In [2]:
def fmtCode(code, length, withInt=False):
    if isinstance(code, float) and math.isnan(code):
        return "NA"
    if withInt:
        if isinstance(code, str) and not code.isdigit():
            return code
        return "0" * (length - len(str(int(code)))) + str(int(code))
    return "0" * (length - len(str(code))) + str(code)

def getBackupValues(row, names):
    for name in names[:-1]:
        if not pd.isna(row[name]):
            return row[name]
    return row[names[-1]]

def getDeptNumber(row):
    return getBackupValues(row, ["department_code", "department_number"])

def getAppropriationAuthority(row):
    return getBackupValues(row, ["org", "appropriation_authority"])

def getAppropriationAmount(row):
    return getBackupValues(row, ["appropration", "_appropriation", "appropriation"])

def getRevisedAppropriationAmount(row):
    return getBackupValues(row, ["_revised_appropriation", "revised_appropriation"])

def getRecommendationAmount(row):
    return getBackupValues(row, ["_recommendation", "recommendation"])

In [3]:
years = list(range(2012, 2026))
df = pd.DataFrame()

for year in years:
    dfYear = pd.read_csv(f"../data/{year}-recommendations.csv")
    dfYear["year"] = year
    df = pd.concat([df, dfYear], ignore_index=True)

# clean rows and columns
df["fund_code"] = df.apply(lambda row: fmtCode(row["fund_code"], 4), axis=1)
df["department_number"] = df.apply(
    lambda row: fmtCode(getDeptNumber(row), 2, True), axis=1
)
df["appropriation_account"] = df["appropriation_account"].apply(
    lambda x: fmtCode(x, 4, True)
)
df["appropriation_authority"] = df.apply(
    lambda row: fmtCode(getAppropriationAuthority(row), 4, True), axis=1
)
df["appropriation"] = df.apply(getAppropriationAmount, axis=1)
df["revised_appropriation"] = df.apply(getRevisedAppropriationAmount, axis=1)
df["recommendation"] = df.apply(getRecommendationAmount, axis=1)
df = df[
    [
        "year",
        "department_number",
        "fund_code",
        "appropriation_account",
        "appropriation_authority",
        "appropriation",
        "revised_appropriation",
        "recommendation",
    ]
]
df.head()

,year,department_number,fund_code,appropriation_account,appropriation_authority,appropriation,revised_appropriation,recommendation
0,2012,01,0100,0229,2005,680.00,680.00,680.00
1,2012,01,0100,0270,2005,872.00,872.00,872.00
2,2012,01,0100,0150,2005,1242.00,1242.00,1000.00
3,2012,01,0100,0126,2005,1310.00,1310.00,1200.00
4,2012,01,0100,0196,2005,0.00,0.00,3800.00

In [4]:
df[
    ~pd.isna(df["appropriation"])
    & ~pd.isna(df["revised_appropriation"])
    & (df["appropriation"] != df["revised_appropriation"])
]

,year,department_number,fund_code,appropriation_account,appropriation_authority,appropriation,revised_appropriation,recommendation
85,2012,15,0100,0700,2005,48000.00,43000.00,43000.00
87,2012,15,0100,9010,2005,107072.00,92072.00,92072.00
94,2012,15,0100,9071,2005,114232.00,0.00,0.00
97,2012,15,0100,0169,2010,5000.00,2500.00,2500.00
101,2012,15,0100,0229,2010,10000.00,8000.00,8000.00
102,2012,15,0100,0140,2010,20000.00,12500.00,12500.00
103,2012,15,0100,0130,2010,20000.00,16000.00,16000.00
108,2012,15,0100,9005,2010,100000.00,50000.00,50000.00
110,2012,15,0100,9010,2010,100000.00,92500.00,92500.00
111,2012,15,0100,0005,2010,1672704.00,1637704.00,1698740.00
113,2012,15,0100,0176,2010,1500.00,0.00,0.00
114,2012,15,0100,9073,2010,50000.00,0.00,0.00
115,2012,15,0100,0140,2015,100000.00,60000.00,60000.00
120,2012,15,0100,0000,2214,508750.00,468750.00,468750.00
121,2012,15,0100,0100,2215,200.00,0.00,0.00
122,2012,15,0100,0300,2215,300.00,0.00,0.00
123,2012,15,0100,0700,2215,500.00,0.00,0.00
124,2012,15,0100,0000,2215,87948.00,0.00,0.00
125,2012,15,0100,0300,2217,1500.00,0.00,0.00
126,2012,15,0100,0700,2217,1500.00,0.00,0.00
127,2012,15,0100,0000,2217,115819.00,0.00,0.00
131,2012,15,0100,0000,2220,107843.00,102843.00,102843.00
133,2012,15,0100,0100,2225,2500.00,17500.00,17500.00
134,2012,15,0100,0000,2225,122081.00,102081.00,102081.00
138,2012,15,0100,0000,2235,129289.00,119289.00,119289.00
142,2012,15,0100,0000,2240,90670.00,87670.00,87670.00
145,2012,15,0100,0000,2245,172960.00,157960.00,157960.00
146,2012,15,0100,0300,2250,4000.00,0.00,0.00
147,2012,15,0100,0700,2250,4000.00,0.00,0.00
148,2012,15,0100,0000,2250,90014.00,0.00,0.00
152,2012,15,0100,0000,2255,114635.00,107635.00,107635.00
155,2012,15,0100,0000,2260,210609.00,200609.00,200609.00
156,2012,15,0100,0100,2270,1500.00,0.00,0.00
157,2012,15,0100,0400,2270,3535.00,0.00,0.00
158,2012,15,0100,0000,2270,108272.00,0.00,0.00
160,2012,15,0100,0300,2275,94700.00,74700.00,74700.00
165,2012,15,0100,0000,2280,202406.00,192406.00,192406.00
167,2012,15,0100,0000,2286,91098.00,88098.00,88098.00
169,2012,15,0100,0300,2290,0.00,5000.00,5000.00
170,2012,15,0100,0100,2290,0.00,30000.00,30000.00
171,2012,15,0100,0000,2290,0.00,479312.00,479312.00
174,2012,15,0100,0000,2295,371209.00,356209.00,356209.00
318,2012,28,0100,0181,2005,900.00,1200.00,1300.00
322,2012,28,0100,0169,2005,5250.00,4950.00,2650.00
445,2012,33,0100,0181,2005,1990.00,3390.00,5000.00
446,2012,33,0100,0152,2005,13030.00,11630.00,6980.00
480,2012,35,0100,0181,2005,7850.00,9350.00,10613.00
487,2012,35,0100,0140,2005,183000.00,181500.00,788000.00
912,2012,56,0100,0149,2005,31850.00,6850.00,1850.00
924,2012,56,0100,0140,2005,110810.00,135810.00,135360.00
1005,2012,58,0100,0039,2705,29170.00,49170.00,29170.00
1023,2012,58,0100,0005,2705,61319680.00,61299680.00,51218819.00
1042,2012,59,0100,0229,2005,281000.00,277000.00,100000.00
1074,2012,59,0100,0245,2005,0.00,3900.00,0.00
1100,2012,67,0100,0149,2005,214400.00,284400.00,345500.00
1101,2012,67,0100,0140,2005,4363897.00,4293897.00,2660897.00
1197,2012,73,0100,0330,2005,100000.00,125000.00,100000.00
1199,2012,73,0100,0342,2005,217186.00,192186.00,216200.00
1530,2012,99,0100,0096,2005,250000.00,322414.00,250000.00
1560,2012,99,0100,0042,2005,198429073.00,198129659.00,192265730.00
1563,2012,99,0100,0055,2005,0.00,77000.00,0.00
1927,2012,15,0300,0000,2230,443054.00,403054.00,403054.00
1928,2012,15,0300,0300,2265,2250.00,5000.00,5000.00
1929,2012,15,0300,0000,2265,346765.00,210000.00,210000.00
2513,2012,15,0355,0100,2155,20394.00,10394.00,10394.00
4324,2012,50,0P36,0005,2815,203600.00,368522.00,400835.00
4329,2012,50,0P36,0005,2868,100396.00,191224.00,195101.00
4373,2012,50,0P40,0005,2903,212418.00,216843.00,227863.00
4401,2012,50,0P40,0005,2904,5757442.00,5931779.00,7275695.00
4604,2012,05,0K38,0157,2505,7000.00,17000.00,17000.00
5007,2013,03,0100,0169,2005,21728.00,36728.00,36525.00
5008,2013,03,0100,0181,2005,42117.00,27117.00,32114.00
5029,2013,05,0100,0245,2005,500.00,1000.00,500.00
5030,2013,05,0100,0270,2005,1000.00,500.00,1000.00
5080,2013,15,0100,0140,2015,60000.00,260000.00,260000.00
5119,2013,15,0100,0000,2286,88098.00,86098.00,88098.00
5120,2013,15,0100,0300,2286,1000.00,3000.00,1000.00
5199,2013,27,0100,0020,2020,57394.00,50602.00,53468.00
5200,2013,27,0100,0039,2020,0.00,6792.00,15000.00
5206,2013,27,0100,0149,2020,121863.00,121363.00,121863.00
5216,2013,27,0100,0181,2020,214968.00,215868.00,170000.00
5217,2013,27,0100,0186,2020,400.00,0.00,0.00
5278,2013,31,0100,0157,2005,7608.00,6358.00,9407.00
5279,2013,31,0100,0162,2005,3390.00,2640.00,3675.00
5286,2013,31,0100,0191,2005,0.00,2000.00,0.00
5320,2013,35,0100,0140,2005,788000.00,738000.00,1174200.00
5325,2013,35,0100,0162,2005,68216.00,118216.00,72800.00
5332,2013,35,0100,0229,2005,200.00,100.00,200.00
5333,2013,35,0100,0245,2005,500.00,1800.00,1500.00
5334,2013,35,0100,0270,2005,2490.00,1290.00,2490.00
5778,2013,59,0100,0229,2005,100000.00,97500.00,75000.00
5779,2013,59,0100,0245,2005,0.00,2500.00,0.00
6205,2013,99,0100,9011,2005,2700000.00,5461227.00,5500000.00
6207,2013,99,0100,9030,2005,3100000.00,2338773.00,3100000.00
6208,2013,99,0100,9076,2005,38055840.00,36055840.00,38023840.00
6214,2013,99,0100,9214,2005,0.00,2500000.00,0.00
7472,2013,85,0740,0229,2015,28500.00,16500.00,2500.00
7473,2013,85,0740,0245,2015,70000.00,82000.00,96000.00
7553,2013,NA,NA,NA,NA,6693285000.00,6695985000.00,6936918000.00
8199,2013,50,0878,0140,2870,422507.00,687507.00,1436463.00
8510,2013,50,0N15,0140,2940,265000.00,0.00,0.00
8733,2013,50,0P36,0140,2868,23146.00,183146.00,0.00
8800,2013,50,0P41,0140,2941,160000.00,0.00,360000.00
9358,2013,NA,NA,NA,NA,8482281000.00,8484981000.00,8743750000.00
9359,2013,NA,NA,NA,NA,8482281000.00,8484981000.00,8743750000.00
9503,2014,15,0100,0000,2286,88098.00,70004.00,88098.00
9504,2014,15,0100,0300,2286,1000.00,19094.00,1000.00
9655,2014,31,0100,0140,2005,1068734.00,1068134.00,1118316.00
9670,2014,31,0100,0191,2005,0.00,600.00,801.00
9682,2014,33,0100,0140,2005,222701.00,239701.00,287835.00
9683,2014,33,0100,0143,2005,88000.00,81000.00,78000.00
9684,2014,33,0100,0149,2005,453010.00,443010.00,7710.00
9715,2014,35,0100,0245,2005,1500.00,2500.00,2500.00
9716,2014,35,0100,0270,2005,2490.00,1490.00,2490.00
9737,2014,38,0100,0005,2126,27056133.00,27229883.00,28442525.00
9742,2014,38,0100,0125,2126,16510148.00,16336398.00,16263982.00
9803,2014,39,0100,0005,2005,6603588.00,6254566.00,6327636.00
9805,2014,39,0100,0020,2005,30680.00,680.00,322715.00
9806,2014,39,0100,0039,2005,0.00,49022.00,0.00
9807,2014,39,0100,0055,2005,100300.00,430300.00,1770660.00
9952,2014,54,0100,0135,2005,1606401.00,1648328.00,1746792.00
9953,2014,54,0100,0138,2005,100000.00,58073.00,80000.00
10143,2014,59,0100,0229,2005,75000.00,71000.00,50000.00
10144,2014,59,0100,0245,2005,0.00,4000.00,0.00
10432,2014,84,0100,0140,2135,15000.00,265000.00,2710000.00
10437,2014,84,0100,0162,2135,19459320.00,19209320.00,11556320.00
10527,2014,99,0100,0042,2005,189775889.00,189563303.00,204657095.00
10536,2014,99,0100,0096,2005,150000.00,362586.00,150000.00
10542,2014,99,0100,0160,2005,0.00,1306000.00,0.00
10561,2014,99,0100,9220,2005,0.00,771000.00,0.00
10563,2014,99,0100,9258,2005,0.00,1250000.00,390370.00
11100,2014,84,0300,0157,2155,286587.00,276487.00,286587.00
11104,2014,84,0300,0181,2155,55000.00,65100.00,87500.00
11354,2014,91,0346,0123,2005,8487.00,88011.00,88011.00
11355,2014,91,0346,0130,2005,84600.00,5076.00,5076.00
11396,2014,15,0355,0000,2155,140326.00,114880.00,146000.00
11399,2014,15,0355,0700,2155,2000.00,27446.00,0.00
11740,2014,35,0740,0245,2005,0.00,1000.00,0.00
11741,2014,35,0740,0270,2005,1000.00,0.00,1000.00
11761,2014,38,0740,0338,2140,2500.00,12500.00,10000.00
11764,2014,38,0740,0360,2140,2550000.00,2540000.00,2669850.00
11830,2014,85,0740,0181,2015,121000.00,201000.00,201000.00
11836,2014,85,0740,0190,2015,987000.00,907000.00,759200.00
12326,2014,41,0H05,0140,2921,239750.00,239048.00,259046.00
12706,2014,70,0J19,0140,2815,0.00,13728.00,0.00
12855,2014,58,0M14,0140,2883,30535362.00,30535366.00,10000000.00
12957,2014,50,0N26,0140,2857,5758963.00,5101963.00,5963730.00
12964,2014,50,0N27,0140,2860,100529548.00,103950401.00,101025895.00
12975,2014,50,0N27,0801,2860,2546791.00,5224636.00,2546791.00
13059,2014,70,0P20,0005,2815,295285.00,294285.00,299323.00
13062,2014,70,0P20,0140,2815,12728.00,0.00,16160.00
13859,2015,15,0100,0000,2255,107635.00,104635.00,107635.00
13861,2015,15,0100,0300,2255,500.00,3500.00,500.00
13883,2015,15,0300,0000,2265,210000.00,164976.00,210000.00
13884,2015,15,0300,0300,2265,5000.00,50024.00,5000.00
14558,2015,38,0100,0140,2140,4262982.00,4212982.00,4240982.00
14567,2015,38,0100,0188,2140,75000.00,125000.00,75000.00
14719,2015,39,0100,0145,2005,588439.00,848439.00,1635075.00
14721,2015,39,0100,0150,2005,229817.00,2817.00,869241.00
14722,2015,39,0100,0152,2005,37502.00,4502.00,171400.00
16154,2015,54,0100,0135,2005,1746792.00,1790617.00,1870269.00
16155,2015,54,0100,0138,2005,80000.00,36175.00,36175.00
16157,2015,54,0100,0141,2005,106750.00,122500.00,121750.00
16159,2015,54,0100,0147,2005,76000.00,60250.00,40000.00
16421,2015,57,0100,0330,1005,195098.00,184098.00,191758.00
16424,2015,57,0100,0342,1005,9966.00,20966.00,9966.00
16728,2015,59,0100,0270,2005,2400.00,1900.00,1900.00
16762,2015,59,0100,0229,2005,50000.00,49000.00,43000.00
16763,2015,59,0100,0245,2005,0.00,1500.00,6000.00
19409,2016,54,0100,0140,2005,1000000.00,1001360.00,881726.00
19417,2016,54,0100,0169,2005,48850.00,47490.00,25466.00
19442,2016,54,0B21,0169,2005,22500.00,21140.00,13800.00
19492,2016,57,0100,0148,1005,525.00,825.00,825.00
19500,2016,57,0100,0169,1005,106630.00,106330.00,109135.00
19985,2016,84,0100,0162,2105,3000.00,2600.00,3000.00
19988,2016,84,0100,0181,2105,2750.00,3150.00,2750.00
20749,2016,99,0610,9982,2005,778218.00,1700979.00,2081372.00
20750,2016,99,0610,9983,2005,1291740.00,2695979.00,2881241.00
20753,2016,99,0683,0976,2005,194122000.00,420000000.00,464000000.00
20754,2016,99,0684,0976,2005,96300000.00,199000000.00,208000000.00
20786,2016,99,0740,9982,2005,2571736.00,5619855.00,6564628.00
20787,2016,99,0740,9983,2005,4642973.00,9689854.00,10293759.00
21969,2017,03,0100,0005,2005,2617186.00,2947054.00,4899380.00
21974,2017,03,0100,0140,2005,105664.00,129796.00,66316.00
22135,2017,15,0100,0120,2015,171000.00,0.00,0.00
22136,2017,15,0100,0137,2015,183000.00,0.00,0.00
22177,2017,15,0100,0000,2295,357543.00,355043.00,362144.00
22178,2017,15,0100,0300,2295,4000.00,6500.00,4000.00
22770,2017,38,0100,0315,2131,3544645.00,4231280.00,3260552.00
22772,2017,38,0100,0320,2131,14602611.00,14856192.00,12702564.00
22776,2017,38,0100,0332,2131,22131208.00,16628188.00,6227293.00
22781,2017,38,0100,0005,2140,31421496.00,34762127.00,35752183.00
22783,2017,38,0100,0012,2140,243841.00,271110.00,277367.00
22784,2017,38,0100,0015,2140,24890.00,26674.00,13936.00
22785,2017,38,0100,0020,2140,400000.00,945817.00,945817.00
22786,2017,38,0100,0140,2140,4259457.00,4559457.00,4459458.00
22789,2017,38,0100,0157,2140,1492199.00,5734021.00,2808999.00
22835,2017,38,0310,0315,2131,686635.00,0.00,0.00
22836,2017,38,0310,0320,2131,253581.00,0.00,0.00
22837,2017,38,0310,0332,2131,0.00,5503020.00,15173076.00
22838,2017,38,0310,0005,2140,3340631.00,0.00,0.00
22839,2017,38,0310,0012,2140,27269.00,0.00,0.00
22840,2017,38,0310,0015,2140,1784.00,0.00,0.00
22841,2017,38,0310,0020,2140,545817.00,0.00,0.00
22842,2017,38,0310,0140,2140,300000.00,0.00,0.00
22843,2017,38,0310,0157,2140,4241822.00,0.00,0.00
23777,2017,84,0100,0229,2145,0.00,1000.00,0.00
23778,2017,84,0100,0245,2145,5500.00,4500.00,5950.00
23785,2017,84,0100,0005,2150,7838690.00,3944171.00,8026900.00
23926,2017,84,0310,0005,2150,0.00,3894519.00,11828596.00
24517,2017,99,0B32,0130,2005,0.00,120000.00,0.00
24518,2017,99,0B32,0140,2005,2000000.00,1880000.00,812160.00
25823,2017,59,0V29,0140,2812,0.00,2690000.00,2750000.00
25826,2017,59,0V30,0140,2810,2690000.00,0.00,1305282.00
26723,2018,99,0100,9291,2005,0.00,1300000.00,1300000.00
27312,2018,57,0100,0157,1005,3756821.00,4356821.00,6564061.00
27588,2018,70,0100,0135,2005,3357039.00,3757039.00,3357039.00
28383,2018,99,0100,0140,2005,41433841.00,44733841.00,38720317.00
28387,2018,99,0100,0157,2005,0.00,500000.00,0.00
28401,2018,99,0100,9030,2005,0.00,1800000.00,0.00
28407,2018,99,0100,9210,2005,0.00,2000000.00,0.00
28408,2018,99,0100,9214,2005,0.00,3500000.00,0.00
28409,2018,99,0100,9292,2005,0.00,2000000.00,0.00
28410,2018,99,0100,9293,2005,0.00,1000000.00,0.00
30113,2019,03,0100,0138,2005,100549.00,150549.00,63549.00
30120,2019,03,0100,0169,2005,101273.00,51273.00,101273.00
30211,2019,05,0100,0140,2005,5500.00,4900.00,5500.00
30212,2019,05,0100,0152,2005,1000.00,800.00,1000.00
30214,2019,05,0100,0169,2005,1000.00,1800.00,1000.00
30218,2019,05,0100,0245,2005,500.00,800.00,500.00
30219,2019,05,0100,0270,2005,500.00,200.00,500.00
30238,2019,06,0100,0245,2005,3150.00,3440.00,5000.00
30239,2019,06,0100,0270,2005,900.00,610.00,900.00
30467,2019,27,0100,0130,2020,461141.00,672141.00,262956.00
30468,2019,27,0100,0138,2020,20500250.00,19690974.00,19350000.00
30469,2019,27,0100,0139,2020,409750.00,10000.00,0.00
30476,2019,27,0100,0159,2020,115666.00,680416.00,109500.00
30477,2019,27,0100,0162,2020,578767.00,1012043.00,718064.00
30581,2019,28,0100,0139,2005,72161.00,63661.00,72161.00
30585,2019,28,0100,0159,2005,4440.00,8440.00,4440.00
30590,2019,28,0100,0190,2005,4000.00,8500.00,1100.00
30648,2019,31,0100,0140,2005,849624.00,847794.00,843424.00
30654,2019,31,0100,0157,2005,57668.00,54668.00,39819.00
30656,2019,31,0100,0162,2005,2477.00,1977.00,2618.00
30658,2019,31,0100,0169,2005,28170.00,33000.00,26071.00
30659,2019,31,0100,0178,2005,8771.00,9271.00,8504.00
30818,2019,99,0100,0135,2005,2150000.00,2888000.00,4275000.00
30821,2019,33,0100,0166,2005,2040.00,1620.00,2040.00
30823,2019,33,0100,0181,2005,3036.00,3456.00,3000.00
30902,2019,38,0100,0340,2103,9500.00,10000.00,9500.00
30903,2019,38,0100,0350,2103,32000.00,31500.00,32000.00
31094,2019,39,0100,0159,2005,532787.00,457787.00,333435.00
31101,2019,39,0100,0190,2005,351258.00,426258.00,539201.00
31259,2019,55,0100,0140,2005,114350.00,114652.00,100026.00
31260,2019,55,0100,0143,2005,70000.00,69348.00,70000.00
31263,2019,55,0100,0181,2005,617.00,967.00,617.00
31285,2019,57,0100,0140,1005,17215573.00,17197853.00,14317419.00
31300,2019,57,0100,0189,1005,312250.00,391600.00,455355.00
31301,2019,57,0100,0190,1005,720000.00,665000.00,595000.00
31303,2019,57,0100,0197,1005,27630.00,21000.00,27630.00
32111,2019,85,0740,0140,2015,96906800.00,96806800.00,101588400.00
32115,2019,85,0740,0147,2015,15000.00,115000.00,15000.00
32224,2019,99,0100,0096,2005,150000.00,211514.00,150000.00
32308,2019,91,0346,0135,2005,500000.00,0.00,0.00
32309,2019,91,0346,0140,2005,390169.00,890169.00,415429.00
32331,2019,99,0100,0003,2005,5731883.00,5670369.00,0.00
32346,2019,99,0100,0140,2005,38720317.00,37982317.00,56780209.00
32355,2019,99,0100,0912,2005,6478572.00,5000000.00,12000000.00
32358,2019,99,0100,0947,2005,0.00,1478572.00,1478572.00
32395,2019,99,0200,0902,2005,123152599.00,120152599.00,112717847.00
32397,2019,99,0200,0912,2005,73835534.00,76835534.00,78304790.00
34234,2020,06,0100,0245,2005,5000.00,5422.00,0.00
34235,2020,06,0100,0270,2005,900.00,478.00,0.00
34261,2020,15,0100,0000,2010,0.00,1041062.00,737210.00
34262,2020,15,0100,0005,2010,1885500.00,0.00,0.00
34264,2020,15,0100,0140,2010,12500.00,18794.00,61520.00
34267,2020,15,0100,0166,2010,2000.00,2129.00,3000.00
34279,2020,15,0100,9010,2010,92500.00,35500.00,35500.00
34282,2020,15,0100,0000,2214,507242.00,470815.00,280000.00
34283,2020,15,0100,0100,2214,15000.00,101725.00,15000.00
34286,2020,15,0100,0700,2214,15000.00,15494.00,15000.00
34287,2020,15,0100,0000,2216,0.00,190000.00,190000.00
34288,2020,15,0100,0100,2216,0.00,1500.00,1500.00
34289,2020,15,0100,0000,2220,111287.00,140000.00,180000.00
34293,2020,15,0100,0000,2223,0.00,110000.00,110000.00
34294,2020,15,0100,0300,2223,0.00,1500.00,1500.00
34295,2020,15,0100,0000,2225,100463.00,163500.00,143500.00
34298,2020,15,0100,0000,2235,164136.00,166199.00,166300.00
34302,2020,15,0100,0000,2240,93609.00,0.00,0.00
34303,2020,15,0100,0100,2240,2506.00,0.00,0.00
34304,2020,15,0100,0300,2240,800.00,0.00,0.00
34308,2020,15,0100,0000,2255,105652.00,385000.00,385000.00
34312,2020,15,0100,0000,2257,0.00,199200.00,205200.00
34313,2020,15,0100,0300,2257,0.00,800.00,800.00
34314,2020,15,0100,0000,2258,0.00,140000.00,143100.00
34315,2020,15,0100,0300,2258,0.00,1500.00,1500.00
34316,2020,15,0100,0000,2260,168387.00,172316.00,168387.00
34320,2020,15,0100,0100,2275,15300.00,74700.00,74700.00
34321,2020,15,0100,0300,2275,74700.00,15300.00,15300.00
34322,2020,15,0100,0000,2277,0.00,140000.00,130000.00
34324,2020,15,0100,0300,2277,0.00,1000.00,4000.00
34327,2020,15,0100,0000,2286,95333.00,0.00,0.00
34328,2020,15,0100,0300,2286,1000.00,0.00,0.00
34329,2020,15,0100,0000,2290,508672.00,387646.00,305100.00
34330,2020,15,0100,0100,2290,40000.00,5000.00,5000.00
34332,2020,15,0100,0000,2295,373008.00,373957.00,373008.00
34334,2020,15,0300,0700,2005,0.00,45325.00,0.00
34335,2020,15,0300,0000,2230,450883.00,370263.00,280000.00
34336,2020,15,0300,0100,2230,0.00,22005.00,15000.00
34337,2020,15,0300,0300,2230,0.00,1387.00,15000.00
34338,2020,15,0300,9000,2230,16387.00,0.00,0.00
34339,2020,15,0300,0000,2265,251710.00,280000.00,280000.00
34412,2020,25,0100,0140,2005,101976.00,100726.00,277530.00
34421,2020,25,0100,0181,2005,0.00,1250.00,2904.00
34466,2020,27,0100,0005,2015,5849271.00,6392343.00,6382482.00
34470,2020,27,0100,0140,2015,234326.00,233476.00,720000.00
34479,2020,27,0100,0181,2015,0.00,850.00,0.00
34605,2020,28,0100,0140,2005,213591.00,243591.00,182484.00
34611,2020,28,0100,0169,2005,37657.00,7657.00,37657.00
34645,2020,30,0100,0138,2005,1048075.00,1115825.00,1065149.00
34646,2020,30,0100,0140,2005,3991688.00,3923438.00,3841838.00
34651,2020,30,0100,0166,2005,2085.00,2585.00,2350.00
34669,2020,31,0100,0140,2005,843424.00,834024.00,902339.00
34679,2020,31,0100,0169,2005,26071.00,35471.00,34107.00
34819,2020,33,0100,0140,2005,350685.00,350300.00,350685.00
34827,2020,33,0100,0181,2005,3000.00,3385.00,3414.00
35101,2020,39,0100,0138,2005,1865188.00,1735188.00,640084.00
35103,2020,39,0100,0143,2005,437000.00,235000.00,21480.00
35104,2020,39,0100,0145,2005,2612810.00,2487810.00,1840090.00
35105,2020,39,0100,0149,2005,1014453.00,1104453.00,1343431.00
35106,2020,39,0100,0150,2005,971945.00,1226945.00,101220.00
35116,2020,39,0100,0178,2005,1653200.00,1765200.00,4860.00
35199,2020,50,0100,0130,2005,2000.00,13000.00,13000.00
35200,2020,50,0100,0135,2005,1325000.00,1314000.00,1350000.00
35258,2020,54,0100,0143,2005,64395.00,71395.00,68195.00
35259,2020,54,0100,0149,2005,58228.00,51228.00,58228.00
35278,2020,54,0B21,0138,2005,120000.00,124500.00,120000.00
35280,2020,54,0B21,0140,2005,10000.00,5500.00,1410000.00
35427,2020,58,0353,0139,2705,7500000.00,6949149.00,11516627.00
35438,2020,58,0353,0196,2705,1631000.00,2181851.00,1531000.00
35729,2020,81,0100,0130,2020,490.00,1490.00,1490.00
35731,2020,81,0100,0157,2020,2928795.00,2927795.00,812280.00
35783,2020,81,0100,0130,2060,120.00,1120.00,120.00
35784,2020,81,0100,0140,2060,1030350.00,1029350.00,1228200.00
35859,2020,84,0100,0140,2105,66000.00,64127.00,50000.00
35860,2020,84,0100,0159,2105,15319.00,17192.00,15319.00
35915,2020,84,0100,0159,2140,5540.00,4980.00,5540.00
35918,2020,84,0100,0181,2140,28200.00,28760.00,32556.00
36021,2020,84,0300,0140,2135,4795000.00,4794419.00,5350000.00
36030,2020,84,0300,0181,2135,34500.00,35081.00,42192.00
36034,2020,84,0300,0229,2135,80000.00,79885.00,80000.00
36035,2020,84,0300,0245,2135,7989.00,8104.00,26550.00
36046,2020,84,0300,0162,2150,12000.00,4577.00,0.00
36047,2020,84,0300,0181,2150,43100.00,50523.00,0.00
36386,2020,99,0100,0042,2005,232749404.00,232617903.00,249578201.00
36396,2020,99,0100,0096,2005,150000.00,281501.00,280000.00
36399,2020,99,0100,0139,2005,10076527.00,10066027.00,9828809.00
36400,2020,99,0100,0140,2005,56030209.00,55517095.00,40423227.00